Update the memory statistics action to use echo groups, change the check for if it runs to be a github workflow step check

diff --git a/memory_statistics/action.yml b/memory_statistics/action.yml
--- a/memory_statistics/action.yml
+++ b/memory_statistics/action.yml
@@ -26,29 +26,51 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Install ARM GCC
+    - env:
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0m
+        stepName: Install ARM GCC
       shell: bash
       run: |
+        # ${{ env.stepName }}
+        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
         wget -qO- "${{ inputs.toolchain_link }}" | sudo tar --strip-components=1 -xj -C /usr/local
+        echo -e "::endgroup::${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
 
-    - name: Compute sizes
-      working-directory: ${{ inputs.path }}
-      shell: bash
-      run: >-
-        ${{ github.action_path }}/memory_statistics.py
-        --config "${{ inputs.config }}"
-        --output "${{ inputs.output }}"
-
-    - name: Compare table
+    - env:
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0m
+        stepName: Compute File Sizes
       working-directory: ${{ inputs.path }}
       shell: bash
       run: |
-        if [ -n "${{ inputs.check_against }}" ] ; then
-            if cmp "${{ inputs.check_against }}" "${{ inputs.output }}" ; then
-                exit 0
-            else
-                echo "Size table does not match!"
-                diff -U 2 "${{ inputs.check_against }}" "${{ inputs.output }}"
-                exit 1
-            fi
+        # ${{ env.stepName }}
+        echo -e "${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        ${{ github.action_path }}/memory_statistics.py --config "${{ inputs.config }}" --output "${{ inputs.output }}"
+        echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+
+    - env:
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0m
+        stepName: Check File Size
+      working-directory: ${{ inputs.path }}
+      shell: bash
+      if: inputs.check_against
+      run: |
+        # ${{ env.stepName }}
+        echo -e "${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        if cmp "${{ inputs.check_against }}" "${{ inputs.output }}" ; then
+          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+            exit 0
+        else
+            echo -e "::endgroup::${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+            echo -e "${{ env.bashFail }} Sizes of files from provided ${{ inputs.check_against }} are not equal to current file size! ${{ env.bashEnd }}"
+            diff -U 2 "${{ inputs.check_against }}" "${{ inputs.output }}"
+            exit 1
         fi
