Print the options that are being added, print the command that is being run

diff --git a/executable-monitor/action.yml b/executable-monitor/action.yml
--- a/executable-monitor/action.yml
+++ b/executable-monitor/action.yml
@@ -46,40 +46,60 @@ runs:
         run: |
           # Run Executable with Monitoring
           echo "::group::Argument Parsing"
-          optArgs=" "
+          optArgs=("")
+          # Make sure we have an exit condition to look for
           if [ "${{ inputs.success-exit-code }}" = "" ] && [ "${{ inputs.success-line }}" = "" ]; then
             echo "::endgroup::"
             echo -e "\033[32;31mDid not supply an input of success-line or success-exit-code to search for\033[0m"
             exit 1
           fi
-          if [ "${{ inputs.success-exit-code }}" != "" ]; then
-             optArgs="--success-exit-code=${{ inputs.success-exit-code }} $optArgs"
-          fi
           
-          if [ "${{ inputs.log-dir }}" != "" ]; then
-            optArgs="--log-dir=${{ inputs.log-dir}} $optArgs"
+          # Check if an exit code was provided
+          if [ "${{ inputs.success-exit-code }}" != "" ]; then
+            echo "Adding --success-exit-code=${{ inputs.success-exit-code }}) to the call"
+            optArgs+=(--success-exit-code=${{ inputs.success-exit-code }})
           fi
 
+          # Check for log directory/if a log file should be created
+          if [ "${{ inputs.log-dir }}" != "" ]; then
+            echo "Adding --log-dir=${{ inputs.log-dir}} to the call"
+            optArgs+=(--log-dir=${{ inputs.log-dir}})
+          fi
+
+          # Check for retry attempts
           if [ "${{ inputs.retry-attempts }}" != "" ]; then
-            optArgs="--retry-attempts=${{ inputs.retry-attempts}} $optArgs"
+            echo "Adding --retry-attempts=${{ inputs.retry-attemps}} to the call"
+            optArgs+=(--retry-attempts=${{ inputs.retry-attempts}})
           fi
-          echo "::endgroup::"
-          
+
+          # Check if a success line was provided. Converting the github input to a bash variable
+          # Will cause it to tokenize on spaces when passed into python
+          # So just only add the success line if it exits.
           if [ "${{ inputs.success-line }}" != "" ]; then
-            echo "python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} $optArgs --success-line="${{ inputs.success-line}}""
-            echo "::group::Executable Output"
-            python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} $optArgs --success-line="${{ inputs.success-line}}"
+              echo "Adding --success-line=${{ inputs.success-line}} to the call"
+              # End the group about parsing the inputs, print the line that will be run
+              echo "::endgroup::"
+              echo -e "\033[1;33mRunning Command: python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} --success-line="${{ inputs.success-line }}" ${optArgs[@]}\033[0m"
           else
-            echo "python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} $optArgs"
-            echo "::group::Executable Output"
-            python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} $optArgs
+              # End the group about parsing the inputs, print the line that will be run
+              echo "::endgroup::"
+              echo -e "\033[1;33mRunning Command: python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} ${optArgs[@]}\033[0m"
           fi
+
+          # Set +e so that an exit code doesn't cause immediately failure. Allows printing exit status string. Create new group
+          set +e
+          echo "::group::Executable Output"
+          python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} ${optArgs[@]}
+
+          # Need to store the status as the endgroup echo will count for the $? check
+          exitStatus=$?
           echo "::endgroup::"
-          if [ "$?" = "0" ]; then
+          if [ "$exitStatus" = "0" ]; then
             echo -e "\033[32;3mValid exit status found\033[0m"
             exit 0
           else
             echo -e "\033[32;31mDid not find a valid exit condition\033[0m"
+            set -e
             exit 1
           fi
         shell: bash
