* CI-CD Overhaul     * Swap to using clang-format instead of uncrustify     * Use a rust spell checker instead of the current one     * Use echo groups to make logs easier to parse     * Add a PR Check that runs against all repos     * Idea of common config templates for repos that use this     ---------

diff --git a/executable-monitor/action.yml b/executable-monitor/action.yml
--- a/executable-monitor/action.yml
+++ b/executable-monitor/action.yml
@@ -13,9 +13,9 @@ inputs:
     required: false
     default: ""
   timeout-seconds:
-    description: 'Maximum amount of time to run the executable. Default is 600.'
+    description: 'Maximum amount of time to run the executable. Default is 180.'
     required: false
-    default: 300
+    default: 180
   retry-attempts:
     description: 'Number of times to re-launch the binary to check for success.'
     required: false
@@ -27,22 +27,33 @@ inputs:
 
 runs:
   using: "composite"
-  steps: 
-      - name: Install Dependencies
+  steps:
+      - env:
+          # The bash escape character is \033
+          # At time of writing, you can't add a global environment to an
+          # action so stuck with this. If this gets changed please move this
+          bashPass:   \033[32;1mPASSED -
+          bashInfo:   \033[33;1mINFO -
+          bashFail:   \033[31;1mFAILED -
+          bashEnd:    \033[0m
+          stepName: Install Dependencies
+        name: ${{ env.stepName }}
+        shell: bash
         run: |
-          # Install Dependencies
+          # ${{ env.stepName }}
           echo "::group::Install Dependencies"
           pip install -r $GITHUB_ACTION_PATH/requirements.txt
+          exitStatus=$?
           echo "::endgroup::"
-          if [ "$?" = "0" ]; then
-            echo -e "\033[32;3mInstalled all dependencies\033[0m"
-            exit 0
-          else
-            echo -e "\033[32;31mDependencies Install failed...\033[0m"
-            exit 1
-          fi
+          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+
+      - env:
+          bashPass: \033[32;1mPASSED -
+          bashInfo: \033[33;1mINFO -
+          bashFail: \033[31;1mFAILED -
+          bashEnd:  \033[0m
+          stepName: ${{ env.stepName }}
         shell: bash
-      - name: Run Executable with Monitoring
         run: |
           # Run Executable with Monitoring
           echo "::group::Argument Parsing"
@@ -50,55 +61,57 @@ runs:
           # Make sure we have an exit condition to look for
           if [ "${{ inputs.success-exit-code }}" = "" ] && [ "${{ inputs.success-line }}" = "" ]; then
             echo "::endgroup::"
-            echo -e "\033[32;31mDid not supply an input of success-line or success-exit-code to search for\033[0m"
+            echo -e "${{ env.bashFail}}Did not supply an input of success-line or success-exit-code to search for ${{ env.bashEnd }}"
             exit 1
           fi
+
+          echo "Adding --exe-path=${{ inputs.exe-path }}"
+          echo "Adding --timeout-seconds=${{ inputs.timeout-seconds }}"
 
           # Check if an exit code was provided
           if [ "${{ inputs.success-exit-code }}" != "" ]; then
             optArgs="--success-exit-code=${{ inputs.success-exit-code }} $optArgs"
-            echo "Adding --success-exit-code=${{ inputs.success-exit-code }} to the call"
+            echo "Adding --success-exit-code=${{ inputs.success-exit-code }}"
           fi
 
           # Check for log directory/if a log file should be created
           if [ "${{ inputs.log-dir }}" != "" ]; then
             optArgs="--log-dir=${{ inputs.log-dir}} $optArgs"
-            echo "Adding --log-dir=${{ inputs.log-dir}} to the call"
+            echo "Adding --log-dir=${{ inputs.log-dir}}"
           fi
 
           # Check for retry attempts
           if [ "${{ inputs.retry-attempts }}" != "" ]; then
             optArgs="--retry-attempts=${{ inputs.retry-attempts }} $optArgs"
-            echo "Adding --retry-attempts=${{ inputs.retry-attempts }} to the call"
+            echo "Adding --retry-attempts=${{ inputs.retry-attempts }}"
           fi
+
+          # set +e so if the run fails we can capture that and print custom error message
+          set +e
 
           # Check if a success line was provided. Converting the github input to a bash variable
           # Will cause it to tokenize on spaces when passed into python
           # So just only add the success line if it exits.
-          # set +e so if the run fails we can capture that and print custom error message
-          set +e
           if [ "${{ inputs.success-line }}" != "" ]; then
             successLineArgs="--success-line=\"${{ inputs.success-line}}\" $optArgs"
-            echo "Adding --success-line=${{ inputs.success-line}} to the call"
+            echo "Adding --success-line=${{ inputs.success-line}}"
             echo "::endgroup::"
-            echo -e "\033[1;33mRunning Command: python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} --success-line="${{ inputs.success-line }}" $optArgs  \033[0m"
+            echo -e " ${{ env.bashInfo }}Running Command: python3 executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} --success-line="${{ inputs.success-line }}" $optArgs ${{ env.bashEnd }}"
             echo "::group::Executable Output"
             python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} $optArgs --success-line="${{ inputs.success-line}}"
           else
             echo "::endgroup::"
-            echo -e "\033[1;33mRunning Command: python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} $optArgs \033[0m"
+            echo -e " ${{ env.bashInfo }}Running Command: python3 executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} $optArgs ${{ env.bashEnd }}"
             echo "::group::Executable Output"
             python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} $optArgs
           fi
           # Store status as the echo group will overwrite it
           exitStatus=$?
           echo "::endgroup::"
-          if [ "$exitStatus" = "0" ]; then
-            echo -e "\033[32;3mValid exit status found\033[0m"
-            exit 0
+          if [ exitStatus -eq 0 ]; then
+            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
           else
-            echo -e "\033[32;31mDid not find a valid exit condition\033[0m"
+            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
             set -e
-            exit 1
           fi
-        shell: bash
+          exit $exitStatus
diff --git a/formatting/action.yml b/formatting/action.yml
--- a/formatting/action.yml
+++ b/formatting/action.yml
@@ -2,78 +2,133 @@ name: 'formatting'
 description: 'CI formatting check'
 inputs:
   path:
-    description: 'Path to repository folder to run formatting check for.'
+    description: 'Path to repository folder to run formatting check for. '
     required: false
     default: ./
   exclude-files:
-    description: 'List of comma-separated files to exclude from trailing whitespace check. Eg file1,file2'
+    description: 'List of comma-separated files to exclude from the formatting check. Eg file1,file2'
     required: false
     default: ''
   exclude-dirs:
-    description: 'List of comma-separated directories to exclude from trailing whitespace formatting check. Eg docs,build'
+    description: 'List of comma-separated directories to exclude from the formatting check. Eg docs,build'
     required: false
     default: ''
+  include-extensions:
+    description: 'List of comma-separated extensions to add to the formatting check . Eg md,dox'
+    required: false
+    default: ''
+
 runs:
   using: "composite"
-  steps: 
-      - name: Install Uncrustify
-        run: |
-          : # Install Uncrustify
-          echo "::group::Install Uncrustify"
-          sudo apt-get install uncrustify
-          echo "::endgroup::"
+  steps:
+      - env:
+          bashPass: \033[32;1mPASSED -
+          bashInfo: \033[33;1mINFO -
+          bashFail: \033[31;1mFAILED -
+          bashEnd:  \033[0m
+          stepName: Install Clang Format
+        name: ${{ env.stepName }}
         shell: bash
-      - name: Run Uncrustify
-        working-directory: ${{ inputs.path }}
         run: |
-          : # Uncrustify on C files while ignoring symlinks.
-          : # Make a collapsible section in the log to run uncrustify
-          echo "::group::Uncrustify Check"
-          : # GitHub automtically use "set -e" which causes scripts to fail on the first exit code
-          : # This would mean the first time a file fails the check that we exit without formatting all files.
-          set +e
-          : # Format all the files using the common config file.
-          find . -iname "*.[ch]" | xargs uncrustify --no-backup --replace --if-changed -c $GITHUB_ACTION_PATH/uncrustify.cfg -l C
+          # ${{ env.stepName }}
+          echo "::group::${{ env.stepName }}"
+          sudo apt-get install clang-format fd-find
+          echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
+          export PATH="$PATH:$GITHUB_ACTION_PATH"
+
+          fdfind --version
+          fdInstalled=$?
+
+          clang-format --version
+          clangFormatInstalled=$?
+
+          getFiles --help
+          getFilesAdded=$?
+
           echo "::endgroup::"
-          : # Run a git diff to print the differences if any exist, return an error code if there are any
+          if [ $getFilesAdded -eq 1 ] || [ $clangFormatInstalled -eq 1] || [ $fdInstalled -eq 1 ]; then
+            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+            exit 1
+          else
+            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+            exit 0
+          fi
+
+      - env:
+          stepName: Validate Inputs
+          # The bash escape character is \033
+          # At time of writing, you can't add a global environment
+          # to an action file so stuck with this. If this gets changed
+          # Please move this
+          bashPass:   \033[32;1mPASSED -
+          bashInfo:   \033[33;1mINFO -
+          bashFail:   \033[31;1mFAILED -
+          bashEnd:    \033[0m
+        name: ${{ env.stepName }}
+        id: validate-inputs
+        shell: bash
+        run: |
+          # ${{ env.stepName }}
+          # Check exclude dirs for possible input issues
+          if [[ "${{ inputs.exclude-dirs }}" = *"\n"* ]]; then
+            echo -e "${{ env.bashFail }} YOU HAVE NEWLINE IN YOUR EXCLUDE-DIRS. ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+
+      - env:
+          stepName: Run Clang Format
+        name: ${{ env.stepName }}
+        if: ${{ steps.validate-inputs.outcome}} = "success"
+        working-directory: ${{ inputs.path }}
+        shell: bash
+        run: |
+          # ${{ env.stepName }}
+          echo -e "${{ env.bashInfo }} Using clang-format version "$(clang-format --version)" ${{ env.bashEnd }}"
+          echo "::group::${{ env.stepName }}"
+          exitCode=0
+          clangError=0
+          export PATH="$PATH:$GITHUB_ACTION_PATH"
+          files=$(getFiles --exclude-files="${{inputs.exclude-files}}" --exclude-dir="${{inputs.exclude-dirs}}" )
+          if [ ! $? -eq 0 ]; then
+              echo -e "${{ env.bashFail }} Error calling getFiles() ${{ env.bashEnd }}"
+              echo -e "$fileOut"
+              exit 1
+          fi
+
+          # set +e
+          # Loop over the files that matched the above conditions
+          for file in ${files[@]}; do
+            # Print them out for future debugging
+            echo -e "${{ env.bashInfo }} Parsing File: "$file" ${{ env.bashEnd }}"
+
+            # Pipe the output of the command to a variable
+            # This way we can print the command only if it fails
+            fileOut=$(clang-format -i --verbose --style=file $file)
+            # If the previous command failed then print out an error message as well as the output
+            if [ ! $? -eq 0 ]; then
+              echo -e "${{ env.bashFail }} Error parsing "$file" ${{ env.bashEnd }}"
+              echo -e "$fileOut"
+              clangError=1
+            fi
+          done
+
+          echo "::endgroup::"
+          # Run a git diff to print the differences if any exist, return an error code if there are any
+
+          echo "::group::File Difference"
           git diff --exit-code
-          if [ "$?" = "0" ]; then
-            echo -e "\033[32;3mUncrustify check passed\033[0m"
-            exit 0
-          else
-            echo -e "\033[32;31mFormatting check (using Uncrustify) failed...\033[0m"
-            : # If there is an error, set this flag high again so the exit 1 fails the run
-            set -e
-            exit 1
+          exitCode=$?
+          echo "::endgroup::"
+          # set -e
+          if [ $clangError -eq 1 ]; then
+            echo -e "${{ env.bashFail }} Clang Encountered an Error ${{ env.bashEnd }}"
           fi
-        shell: bash
-      - name: Check For Trailing Whitespace
-        working-directory: ${{ inputs.path }}
-        run: |
-          : # Trailing Whitespace Check
-          set +e
-          grep --exclude={README.md,${{ inputs.exclude-files }}} --exclude-dir={${{ inputs.exclude-dirs }},'.git'} -rnI -e "[[:blank:]]$" .
-          if [ "$?" = "0" ]; then
-            set -e
-            echo -e "\033[32;31mFiles have trailing whitespace.\033[0m"
-            exit 1
+
+          if [ $exitCode -eq 0 ]; then
+            echo -e "${{ env.bashPass }} ${{env.stepName }} ${{ env.bashEnd }}"
           else
-            echo -e "\033[32;3mTrailing whitespace check passed\033[0m"
-            exit 0
+            echo -e "${{ env.bashFail }} List of files with formatting errors: ${{ env.bashEnd }}"
+            echo -e "${{ env.bashFail }} "$(git diff --name-only)" ${{ env.bashEnd }} "
+            echo -e "${{ env.bashFail }} ${{env.stepName }} ${{ env.bashEnd }}"
           fi
-        shell: bash
-      - name: Check for CRLF
-        working-directory: ${{ inputs.path }}
-        run: |
-          : # Check for CRLF Line Ending
-          set +e
-          find . -path ./.git -prune -o -exec file {} + |  grep "CRLF"
-          if [ "$?" = "0" ]; then
-            set -e
-            echo -e "\033[32;31mFiles have CRLF line endings.\033[0m"
-            exit 1
-          else
-            echo -e "\033[32;3mLine ending check passed\033[0m"
-            exit 0
-          fi
-        shell: bash
+          exit $exitCode || $clangError
