Action File Formatting Updates (#85)
* Update the actions to use 2 spaces for tabs instead of 4. Small tweaks to clang-formatting action file to make it identical to the uncrustify one
* Update one of the manifest-verifier debug print statements to make more sense
* Update the memory statistics action to use echo groups, change the check for if it runs to be a github workflow step check
* Update the spell check to run silently so it doesn't flood the log with the line of each file. Relevant for use in large repos where this could run against thousands of files
* Use echo groups for doxygen action

diff --git a/coverage-cop/action.yml b/coverage-cop/action.yml
--- a/coverage-cop/action.yml
+++ b/coverage-cop/action.yml
@@ -15,92 +15,93 @@ inputs:
 runs:
   using: "composite"
   steps:
-      - env:
-          stepName: Install Dependencies
-          bashPass: \033[32;1mPASSED -
-          bashInfo: \033[33;1mINFO -
-          bashFail: \033[31;1mFAILED -
-          bashEnd:  \033[0
-        shell: bash
-        name: ${{ env.stepName }}
-        run: |
-          # ${{ env.stepName }}
-          echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          sudo apt-get install lcov fd-find
+    - env:
+        stepName: Install Dependencies
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0
+      name: ${{ env.stepName }}
+      shell: bash
+      run: |
+        # ${{ env.stepName }}
+        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        sudo apt-get install lcov fd-find
+        echo -e "::endgroup::"
+        echo -e "${{ env.bashPass }} ${{env.stepName }} ${{ env.bashEnd }}"
+
+    - env:
+        stepName: Check Line and Branch Coverage
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0
+      name: ${{ env.stepName }}
+      id: action-check-line-and-branch-coverage
+      shell: bash
+      run: |
+        # ${{ env.stepName }}
+
+        # Print the received code cov report.
+        # TODO: The way it grabs the line/branch coverage is a little complicated
+        # I'd like to see if this can be done simpler.
+        echo -e " ${{ env.bashInfo }} Received LCov Report: ${{ inputs.coverage-file }} ${{ env.bashEnd}}"
+        lcov --list --rc lcov_branch_coverage=1 ${{ inputs.coverage-file }}
+        LINE_COVERAGE=$(lcov --list ${{ inputs.coverage-file }} | tail -n 1 | cut -d '|' -f 2 | sed -n "s/\([^%]*\)%.*/\1/p")
+        BRANCH_COVERAGE=$(lcov --rc lcov_branch_coverage=1 --list ${{ inputs.coverage-file }} | tail -n 1 | cut -d '|' -f 4 | sed -n "s/\([^%]*\)%.*/\1/p")
+        RESULT=0
+
+        # Check Line Coverage
+        echo -e " ${{ env.bashInfo }} Required Line Coverage: ${{ inputs.line-coverage-min }} ${{ env.bashEnd}}"
+        echo -e " ${{ env.bashInfo }} Line Coverage of PR: $LINE_COVERAGE ${{ env.bashEnd}}\n"
+        if [[ $(echo "$LINE_COVERAGE < ${{ inputs.line-coverage-min }}" | bc) -ne 0 ]]; then
+          echo -e "${{ env.bashFail }} Line Coverage is too low. ${{ env.bashEnd }}"
+          RESULT=1
+        fi
+
+        echo -e " ${{ env.bashInfo }} Required Branch Coverage: ${{ inputs.branch-coverage-min }} ${{ env.bashEnd}}"
+        echo -e " ${{ env.bashInfo }} Line Coverage of PR: $BRANCH_COVERAGE ${{ env.bashEnd}}"
+        if [[ $(echo "$BRANCH_COVERAGE < ${{ inputs.branch-coverage-min }}" | bc) -ne 0 ]]; then
+          echo -e "${{ env.bashFail }} Branch Coverage is too low. ${{ env.bashEnd }}"
+          RESULT=1
+        fi
+
+        if [ $RESULT -eq 0 ]; then
+          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        else
+          echo -e "::group::Create Failed Codecov HTML Report"
+          genhtml --rc lcov_branch_coverage=1 --ignore-errors source ${{ inputs.coverage-file }} --legend --title "$(basename `git rev-parse --show-toplevel`) $(git rev-parse HEAD)" --output-directory=CodecovHTMLReport
+          zip -r CodecovHTMLReport.zip CodecovHTMLReport
           echo -e "::endgroup::"
-          echo -e "${{ env.bashPass }} ${{env.stepName }} ${{ env.bashEnd }}"
+          echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        fi
+        exit $RESULT
 
-      - env:
-          stepName: Check Line and Branch Coverage
-          bashPass: \033[32;1mPASSED -
-          bashInfo: \033[33;1mINFO -
-          bashFail: \033[31;1mFAILED -
-          bashEnd:  \033[0
-        name: ${{ env.stepName }}
-        id: action-check-line-and-branch-coverage
-        shell: bash
-        run: |
-          # ${{ env.stepName }}
+    - name: Upload Failed Codecov HTML Report
+      if: failure() && ( steps.action-check-line-and-branch-coverage.outcome == 'failure' )
+      id: upload-codecov-report
+      uses: actions/upload-artifact@v3
+      with:
+        name: CodecovHTMLReport
+        path: CodecovHTMLReport.zip
+        retention-days: 5
 
-          # Print the received code cov report.
-          # TODO: The way it grabs the line/branch coverage is a little complicated
-          # I'd like to see if this can be done simpler.
-          echo -e " ${{ env.bashInfo }} Received LCov Report: ${{ inputs.line-coverage-min }} ${{ env.bashEnd}}"
-          lcov --list --rc lcov_branch_coverage=1 ${{ inputs.coverage-file }}
-          LINE_COVERAGE=$(lcov --list ${{ inputs.coverage-file }} | tail -n 1 | cut -d '|' -f 2 | sed -n "s/\([^%]*\)%.*/\1/p")
-          BRANCH_COVERAGE=$(lcov --rc lcov_branch_coverage=1 --list ${{ inputs.coverage-file }} | tail -n 1 | cut -d '|' -f 4 | sed -n "s/\([^%]*\)%.*/\1/p")
-          RESULT=0
-
-          # Check Line Coverage
-          echo -e " ${{ env.bashInfo }} Required Line Coverage: ${{ inputs.line-coverage-min }} ${{ env.bashEnd}}"
-          echo -e " ${{ env.bashInfo }} Received Line Coverage: $LINE_COVERAGE ${{ env.bashEnd}}"
-          if [[ $(echo "$LINE_COVERAGE < ${{ inputs.line-coverage-min }}" | bc) -ne 0 ]]; then
-            echo -e "${{ env.bashFail }} Line Coverage is too low. ${{ env.bashEnd }}"
-            RESULT=1
-          fi
-
-          echo -e " ${{ env.bashInfo }} Required Branch Coverage: ${{ inputs.branch-coverage-min }} ${{ env.bashEnd}}"
-          echo -e " ${{ env.bashInfo }} Received Branch Coverage: $BRANCH_COVERAGE ${{ env.bashEnd}}"
-          if [[ $(echo "$BRANCH_COVERAGE < ${{ inputs.branch-coverage-min }}" | bc) -ne 0 ]]; then
-            echo -e "${{ env.bashFail }} Branch Coverage is too low. ${{ env.bashEnd }}"
-            RESULT=1
-          fi
-
-          if [ $RESULT -eq 0 ]; then
-            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          else
-            echo -e "::group::Create Failed Codecov HTML Report"
-            genhtml --rc lcov_branch_coverage=1 --ignore-errors source ${{ inputs.coverage-file }} --legend --title "$(basename `git rev-parse --show-toplevel`) $(git rev-parse HEAD)" --output-directory=CodecovHTMLReport
-            zip -r CodecovHTMLReport.zip CodecovHTMLReport
-            echo -e "::endgroup::"
-            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          fi
-          exit $RESULT
-
-      - name: Upload Failed Codecov HTML Report
-        if: failure() && ( steps.action-check-line-and-branch-coverage.outcome == 'failure' )
-        id: upload-codecov-report
-        uses: actions/upload-artifact@v3
-        with:
-          name: CodecovHTMLReport
-          path: CodecovHTMLReport.zip
-          retention-days: 5
-
-      - env:
-          stepName: Codecov Report Info
-          bashPass: \033[32;1m
-          bashInfo: \033[33;1m
-          bashFail: \033[31;1m
-          bashEnd:  \033[0
-        if: failure() && ( steps.upload-codecov-report.outcome == 'success' )
-        shell: bash
-        run: |
-          # ${{ env.stepName }}
-          echo -e "${{ env.bashInfo }} A zip file of the failed Codecov report has been attached to this workflow ${{ env.bashEnd }}"
-          echo -e "${{ env.bashInfo }} This can be accessed by returning to the bottom of the summary page of the workflow run ${{ env.bashEnd }}"
-          echo -e "${{ env.bashInfo }} At the bottom of the page will be a CodecovHTMLReport.zip file that you can download ${{ env.bashEnd }}"
-          echo -e "${{ env.bashInfo }} Unzip the file and then open the index.html file in your browser for more info missing branch and line coverage ${{ env.bashEnd }}"
-          exit 1
+    - env:
+        stepName: Codecov Report Info
+        bashPass: \033[32;1m
+        bashInfo: \033[33;1m
+        bashFail: \033[31;1m
+        bashEnd:  \033[0
+      name: ${{ env.stepName }}
+      if: failure() && ( steps.upload-codecov-report.outcome == 'success' )
+      shell: bash
+      run: |
+        # ${{ env.stepName }}
+        echo -e "${{ env.bashInfo }} A zip file of the failed Codecov report has been attached to this workflow ${{ env.bashEnd }}"
+        echo -e "${{ env.bashInfo }} This can be accessed by returning to the bottom of the summary page of the workflow run ${{ env.bashEnd }}"
+        echo -e "${{ env.bashInfo }} At the bottom of the page will be a CodecovHTMLReport.zip file that you can download ${{ env.bashEnd }}"
+        echo -e "${{ env.bashInfo }} Unzip the file and then open the index.html file in your browser for more info missing branch and line coverage ${{ env.bashEnd }}"
+        exit 1
 
 
 
@@ -111,13 +112,13 @@ runs:
 # CorePKCS11 evidently has this, but I don't know who set that up or what approvals it took
 # So For now I'm going to create the html report and add it to the run.
 # More info here: https://about.Codecov.io/blog/how-to-set-up-Codecov-with-c-and-github-actions/
-#      - env:
-#          stepName: Upload Line and Branch Report
-#        name: ${{ env.stepName }}
-#        if: failure()
-#        uses: Codecov/Codecov-action@v3
-#        with:
-#          files: ${{ inputs.coverage-file }}
-#          flags: unit_tests
-#          fail_ci_if_error: false
-#          verbose: false
+#    - env:
+#        stepName: Upload Line and Branch Report
+#      name: ${{ env.stepName }}
+#      if: failure()
+#      uses: Codecov/Codecov-action@v3
+#      with:
+#        files: ${{ inputs.coverage-file }}
+#        flags: unit_tests
+#        fail_ci_if_error: false
+#        verbose: false
diff --git a/memory_statistics/action.yml b/memory_statistics/action.yml
--- a/memory_statistics/action.yml
+++ b/memory_statistics/action.yml
@@ -22,30 +22,60 @@ inputs:
     description: 'Link to ARM GCC tar.bz2 to use for compiling files (default version 9-2020-q2).'
     required: false
     default: "https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2?revision=05382cca-1721-44e1-ae19-1e7c3dc96118&la=en&hash=D7C9D18FCA2DD9F894FD9F3C3DC9228498FA281A"
+
 runs:
   using: "composite"
   steps:
-    - name: Install ARM GCC
+    - env:
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0m
+        stepName: Install ARM GCC
+      name: ${{ env.stepName }}
+      shell: bash
       run: |
-          wget -qO- "${{ inputs.toolchain_link }}" | sudo tar --strip-components=1 -xj -C /usr/local
-      shell: bash
-    - name: Compute sizes
+        # ${{ env.stepName }}
+        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        wget -qO- "${{ inputs.toolchain_link }}" | sudo tar --strip-components=1 -xj -C /usr/local
+        echo -e "::endgroup::"
+        echo -e "::group::${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+
+    - env:
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0m
+        stepName: Compute File Sizes
+      name: ${{ env.stepName }}
       working-directory: ${{ inputs.path }}
-      run: >-
-          ${{ github.action_path }}/memory_statistics.py
-          --config "${{ inputs.config }}"
-          --output "${{ inputs.output }}"
       shell: bash
-    - name: Compare table
-      working-directory: ${{ inputs.path }}
       run: |
-          if [ -n "${{ inputs.check_against }}" ] ; then
-              if cmp "${{ inputs.check_against }}" "${{ inputs.output }}" ; then
-                  exit 0
-              else
-                  echo "Size table does not match!"
-                  diff -U 2 "${{ inputs.check_against }}" "${{ inputs.output }}"
-                  exit 1
-              fi
-          fi
+        # ${{ env.stepName }}
+        echo -e "${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        ${{ github.action_path }}/memory_statistics.py --config "${{ inputs.config }}" --output "${{ inputs.output }}"
+        echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+
+    - env:
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0m
+        stepName: Check File Size
+      name: ${{ env.stepName }}
+      working-directory: ${{ inputs.path }}
       shell: bash
+      if: inputs.check_against
+      run: |
+        # ${{ env.stepName }}
+        echo -e "${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        if cmp "${{ inputs.check_against }}" "${{ inputs.output }}" ; then
+          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          exit 0
+        else
+          echo -e "::endgroup::"
+          echo -e "::group::${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          echo -e "${{ env.bashFail }} Sizes of files from provided ${{ inputs.check_against }} are not equal to current file size! ${{ env.bashEnd }}"
+          diff -U 2 "${{ inputs.check_against }}" "${{ inputs.output }}"
+          exit 1
+        fi
