Typos

diff --git a/formatting/action.yml b/formatting/action.yml
--- a/formatting/action.yml
+++ b/formatting/action.yml
@@ -53,8 +53,13 @@ runs:
           # Yes this breaks the ability to have files/directories with spaces.
           # But that breaks most UNIX commands. Including the following grep glob.
           # These variables can then be seen in the log, as well as accessed from future steps
-          echo "excludeFiles$(echo "${{inputs.exclude-files}})" | sed 's/ //g') >> "$GITHUB_ENV"
-          echo "excludeDirs=$(echo "${{inputs.exclude-dirs}})" | sed 's/ //g')" >> "$GITHUB_ENV"
+          if [[ "${{inputs.exclude-files}}" != " "]]; then
+            echo "excludeFiles=$(echo ${{inputs.exclude-files}} | sed 's/ //g') >> "$GITHUB_ENV"
+          fi
+
+          if [[ "${{inputs.exclude-dirs}}" != " "]]; then
+            echo "excludeDirs=$(echo ${{inputs.exclude-dirs}} | sed 's/ //g')" >> "$GITHUB_ENV"
+          fi
 
       - env:
           stepName: Run Uncrustify
@@ -65,7 +70,7 @@ runs:
           # Uncrustify on C files while ignoring symlinks.
           echo "::group::Uncrustify Check"
 
-          # GitHub automtically use "set -e" which causes scripts to fail on the first exit code
+          # GitHub automatically use "set -e" which causes scripts to fail on the first exit code
           # This would mean the first time a file fails the check that we exit without formatting all files.
           set +e
 
