Handle the merge conflicts, grab the most recent version of the actions. Update the PR check action to take in a branch, point it back to my forks

diff --git a/formatting/action.yml b/formatting/action.yml
--- a/formatting/action.yml
+++ b/formatting/action.yml
@@ -6,10 +6,10 @@ inputs:
     required: false
     default: ./
   exclude-files:
-    description: 'List of comma-separated files to exclude from formatting check. Eg file1, file2'
+    description: 'List of comma-separated files to exclude from the formatting check. Eg file1, file2'
     required: false
   exclude-dirs:
-    description: 'List of comma-separated directories to exclude from formatting check. Eg docs, build'
+    description: 'List of comma-separated directories to exclude from the formatting check. Eg docs, build'
     required: false
   include-extensions:
     description: 'List of comma-separated extensions to add to the formatting check. Eg md, dox'
@@ -19,24 +19,38 @@ runs:
   using: "composite"
   steps:
       - env:
+          # At time of writing, you can't add a global environment
+          # to an action file so stuck with this. If this gets changed
+          # Please move this
           bashPass: \033[32;1mPASSED -
           bashInfo: \033[33;1mINFO -
           bashFail: \033[31;1mFAILED -
           bashEnd:  \033[0m
           stepName: Install Uncrustify
+        name: ${{ env.stepName }}
         shell: bash
         run: |
           # ${{ env.stepName }}
           echo -e "::group::${{ env.stepName }}"
           sudo apt-get install uncrustify fd-find dos2unix
+          echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
+          export PATH="$PATH:$GITHUB_ACTION_PATH"
+
+          fdfind --version
+          fdInstalled=$?
+
+          uncrustify --version
+          uncrustifyInstalled=$?
+
           echo -e "::endgroup::"
+          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
 
       - env:
           bashPass: \033[32;1mPASSED -
           bashInfo: \033[33;1mINFO -
           bashFail: \033[31;1mFAILED -
           bashEnd:  \033[0m
-          stepName: Run Uncrustify
+          stepName: Formatting Check
         name: ${{ env.stepName }}
         id: action-formatting-check
         working-directory: ${{ inputs.path }}
@@ -44,6 +58,14 @@ runs:
         run: |
           # ${{ env.stepName }}
           echo -e "${{ env.bashInfo }} Using Uncrustify Version "$(uncrustify --version)" ${{ env.bashEnd }}"
+
+          exitCode=0
+          export PATH="$PATH:$GITHUB_ACTION_PATH"
+
+          # TODO: These checks should really only run against modified files on PRS
+          # Where when the commit to the actual repo happens, then we should trigger the job
+          # Against all of the files in the repo. Nice inbetween to keep checks fast for PRs,
+          # But maintain that we don't have a change in the Repo that suddenly causes an issue
 
           # Parse the optional inputs
           args=""
@@ -74,42 +96,37 @@ runs:
 
           # Get all .c and .h files, as well as any other requested file types.
           # Then run uncrustify with the common config file.
-          echo -e "${{ env.bashInfo }} Running: fdfind -e c -e h ${args} --exec uncrustify --no-backup --replace --if-changed -c $GITHUB_ACTION_PATH/uncrustify.cfg -l C ${{ env.bashEnd }}"
-          echo -e "::group::${{ env.bashInfo }} Check Formatting with Uncrustify ${{ env.bashEnd }}"
-          fdfind -e c -e h ${args} --exec uncrustify --no-backup --replace --if-changed -c $GITHUB_ACTION_PATH/uncrustify.cfg -l C
-          echo -e "::endgroup::"
+          echo -e "::group::${{ env.bashInfo }} Check Formatting ${{ env.bashEnd }}"
+          echo -e "${{ env.bashInfo }} fdfind -e c -e h ${args} --exec uncrustify --no-backup --replace --if-changed -c https://github.com/FreeRTOS/CI-CD-Github-Actions/blob/main/formatting/uncrustify.cfg -l C ${{ env.bashEnd }}"
+          fdfind -e c -e h ${args} --exec uncrustify -q --no-backup --replace --if-changed -c $GITHUB_ACTION_PATH/uncrustify.cfg -l C
 
-          echo -e "::group::${{ env.bashInfo }} Check for Trailing Whitespace ${{ env.bashEnd }}"
-          # These checks will be captured in the git diff
-          # Replace all trailing whitespace, exclude photo files and args
-          fdfind --type=file -E '*.png' -E '*.jpg' -E '*.svg' ${args} . --exec sed -Ei 's/[[:blank:]]+$//'
-          echo -e "::endgroup::"
+          # Replace all trailing whitespace, exclude photo and binary files
+          echo -e "${{ env.bashInfo }} Check for Trailing Whitespace ${{ env.bashEnd }}"
+          echo -e "${{ env.bashInfo }} fdfind --type=file -E '*.png' -E '*.jpg' -E '*.svg' -E '*.a' -E '*.lib' -E '*.patch' ${args} . --exec sed -Ei 's/[[:blank:]]+$//' ${{ env.bashEnd }}"
+          fdfind --type=file -E '*.png' -E '*.jpg' -E '*.svg' -E '*.a' -E '*.lib' -E '*.patch' ${args} . --exec sed -Ei 's/[[:blank:]]+$//'
 
-          echo -e "::group::${{ env.bashInfo }} Check for CRLF Line Endings ${{ env.bashEnd }}"
           # Replace all line endings with LF ones instead of CRLF
-          fdfind --type=file ${args} . --exec dos2unix
-          echo -e "::endgroup::"
+          echo -e "${{ env.bashInfo }} Check for CRLF Line Endings ${{ env.bashEnd }}"
+          echo -e "${{ env.bashInfo }} fdfind --type=file ${args} . --exec dos2unix ${{ env.bashEnd }}"
+          fdfind --type=file ${args} . --exec dos2unix -q
 
-          # Run a git diff to print the differences if any exist, return an error code if there are any
-          # Wrap in a set+e and set -e so we can keep running after the error
-          echo -e "::group::${{ env.bashInfo }} Format Difference ${{ env.bashEnd }}"
+          # Determine if there was a formatting diff.
+          # If there was, create a patch of it.
           set +e
-          git diff --exit-code --color=always
+          git diff --exit-code >> formattingChanges.patch
           exitCode=$?
           set -e
-          echo -e "::endgroup::"
 
           if [ $exitCode -eq 0 ]; then
-            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+              echo -e "::endgroup::"
+              echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
           else
-            # I am intentionally doing this a second time here.
-            # Using tee will mask the exit code of the diff
-            # And we don't want the colour to be added to the patch
-            # Put it in what the 'default' path will be for the upload step
-            git diff > formattingChanges.patch
-            echo -e "${{ env.bashFail }} List of files with formatting errors: ${{ env.bashEnd }}"
-            echo -e "${{ env.bashFail }} "$(git diff --name-only)" ${{ env.bashEnd }} "
-            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+              # Run a git diff to print the formatting differences
+              echo -e "::group::${{ env.bashInfo }} Format Difference ${{ env.bashEnd }}"
+              git diff --color=always
+              echo -e "::endgroup::${{ env.bashFail }} List of files with formatting errors: ${{ env.bashEnd }}"
+              echo -e "${{ env.bashFail }} "$(git diff --name-only)" ${{ env.bashEnd }} "
+              echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
           fi
           exit $exitCode
 
