Update the actions to use 2 spaces for tabs instead of 4. Small tweaks to clang-formatting action file to make it identical to the uncrustify one

diff --git a/clang-formatting/action.yml b/clang-formatting/action.yml
--- a/clang-formatting/action.yml
+++ b/clang-formatting/action.yml
@@ -18,140 +18,133 @@ inputs:
 runs:
   using: "composite"
   steps:
-      - env:
-          # At time of writing, you can't add a global environment
-          # to an action file so stuck with this. If this gets changed
-          # Please move this
-          bashPass: \033[32;1mPASSED -
-          bashInfo: \033[33;1mINFO -
-          bashFail: \033[31;1mFAILED -
-          bashEnd:  \033[0m
-          stepName: Install Clang Format
-        name: ${{ env.stepName }}
-        shell: bash
-        run: |
-          # ${{ env.stepName }}
-          echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          sudo apt-get install clang-format fd-find dos2unix
-          echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
-          export PATH="$PATH:$GITHUB_ACTION_PATH"
+    - env:
+        # At time of writing, you can't add a global environment
+        # to an action file so stuck with this. If this gets changed
+        # Please move this
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0m
+        stepName: Install Clang Format
+      name: ${{ env.stepName }}
+      shell: bash
+      run: |
+        # ${{ env.stepName }}
+        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
 
-          fdfind --version
-          fdInstalled=$?
+        sudo apt-get install clang-format fd-find dos2unix
+        echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
+        export PATH="$PATH:$GITHUB_ACTION_PATH"
 
-          clang-format --version
-          clangFormatInstalled=$?
+        # Check that the commands installed correctly
+        fdfind --version
+        echo -e "::endgroup::"
 
-          echo -e "::endgroup::"
-          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        echo -e "${{ env.bashInfo }} Using clang-format Version "$(clang-format --version)" ${{ env.bashEnd }}"
+        echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
 
-      - env:
-          bashPass: \033[32;1mPASSED -
-          bashInfo: \033[33;1mINFO -
-          bashFail: \033[31;1mFAILED -
-          bashEnd:  \033[0m
-          stepName: Formatting Check
-        name: ${{ env.stepName }}
-        id: action-formatting-check
-        working-directory: ${{ inputs.path }}
-        shell: bash
-        run: |
-          # ${{ env.stepName }}
-          echo -e "${{ env.bashInfo }} Using clang-format Version "$(clang-format --version)" ${{ env.bashEnd }}"
+    - env:
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0m
+        stepName: Formatting Check
+      name: ${{ env.stepName }}
+      id: action-formatting-check
+      working-directory: ${{ inputs.path }}
+      shell: bash
+      run: |
+        # ${{ env.stepName }}
+        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
 
-          exitCode=0
-          export PATH="$PATH:$GITHUB_ACTION_PATH"
+        exitCode=0
+        export PATH="$PATH:$GITHUB_ACTION_PATH"
 
-          # TODO: These checks should really only run against modified files on PRS
-          # Where when the commit to the actual repo happens, then we should trigger the job
-          # Against all of the files in the repo. That way we can keep checks fast for PRs,
-          # and maintain that we don't have a change in the Repo.
-          # Think this can be done with git clang-format:
-          # https://ortogonal.github.io/cpp/git-clang-format/
+        # Parse the optional inputs
+        args=""
 
-          # Parse the optional inputs
-          args=""
+        # fd-find uses -E to exclude a file or directory
+        if [ -n "${{ inputs.exclude-dirs }}" ]; then
+          dirs=" -E "
+          dirs+="${{ inputs.exclude-dirs }}"
+          dirs="${dirs//,/ -E }"
+          args+=" ${dirs}"
+        fi
 
-          # fd-find uses -E to exclude a file or directory
-          if [ -n "${{ inputs.exclude-dirs }}" ]; then
-            dirs=" -E "
-            dirs+="${{ inputs.exclude-dirs }}"
-            dirs="${dirs//,/ -E }"
-            args+=" ${dirs}"
-          fi
+        # fd-find uses -E to exclude a file or directory
+        if [ -n "${{ inputs.exclude-files }}" ]; then
+          files=" -E "
+          files+="${{ inputs.exclude-files }}"
+          files="${files//,/ -E }"
+          args+=" ${files}"
+        fi
 
-          # fd-find uses -E to exclude a file or directory
-          if [ -n "${{ inputs.exclude-files }}" ]; then
-            files=" -E "
-            files+="${{ inputs.exclude-files }}"
-            files="${files//,/ -E }"
-            args+=" ${files}"
-          fi
+        # fd-find uses -e to include a file extension
+        if [ -n "${{ inputs.include-file-types }}" ]; then
+          file_types=" -e "
+          file_types+="${{ inputs.include-file-types }}"
+          file_types="${file_types//,/ -e }"
+          args+=" ${file_types}"
+        fi
 
-          # fd-find uses -e to include a file extension
-          if [ -n "${{ inputs.include-file-types }}" ]; then
-            file_types=" -e "
-            file_types+="${{ inputs.include-file-types }}"
-            file_types="${file_types//,/ -e }"
-            args+=" ${file_types}"
-          fi
+        # Get all .c and .h files, as well as any other requested file types.
+        # Then run clang-format with the common config file.
 
-          # Get all .c and .h files, as well as any other requested file types.
-          # Then run clang-format with the common config file.
-          echo -e "::group::${{ env.bashInfo }} Check Formatting ${{ env.bashEnd }}"
-          echo -e "${{ env.bashInfo }} fdfind -e c -e h ${args} --exec clang-format -i ${{ env.bashEnd }}"
-          fdfind -e c -e h ${args} --exec clang-format --verbose -i
+        echo -e "${{ env.bashInfo }} fdfind -e c -e h ${args} --exec clang-format -i ${{ env.bashEnd }}"
+        fdfind -e c -e h ${args} --exec clang-format --verbose -i
 
-          # Replace all trailing whitespace, exclude photo and binary files
-          echo -e "${{ env.bashInfo }} Check for Trailing Whitespace ${{ env.bashEnd }}"
-          echo -e "${{ env.bashInfo }} fdfind --type=file -E '*.png' -E '*.jpg' -E '*.svg' -E '*.a' -E '*.lib' -E '*.patch' ${args} . --exec sed -Ei 's/[[:blank:]]+$//' ${{ env.bashEnd }}"
-          fdfind --type=file -E '*.png' -E '*.jpg' -E '*.svg' -E '*.a' -E '*.lib' -E '*.patch' ${args} . --exec sed -Ei 's/[[:blank:]]+$//'
+        # Replace all trailing whitespace, exclude photo and binary files
+        echo -e "${{ env.bashInfo }} Check for Trailing Whitespace ${{ env.bashEnd }}"
+        echo -e "${{ env.bashInfo }} fdfind --type=file -E '*.png' -E '*.jpg' -E '*.svg' -E '*.a' -E '*.lib' -E '*.patch' ${args} . --exec sed -Ei 's/[[:blank:]]+$//' ${{ env.bashEnd }}"
+        fdfind --type=file -E '*.png' -E '*.jpg' -E '*.svg' -E '*.a' -E '*.lib' -E '*.patch' ${args} . --exec sed -Ei 's/[[:blank:]]+$//'
 
-          # Replace all line endings with LF ones instead of CRLF
-          echo -e "${{ env.bashInfo }} Check for CRLF Line Endings ${{ env.bashEnd }}"
-          echo -e "${{ env.bashInfo }} fdfind --type=file ${args} . --exec dos2unix ${{ env.bashEnd }}"
-          fdfind --type=file ${args} . --exec dos2unix -q
+        # Replace all line endings with LF ones instead of CRLF
+        echo -e "${{ env.bashInfo }} Check for CRLF Line Endings ${{ env.bashEnd }}"
+        echo -e "${{ env.bashInfo }} fdfind --type=file ${args} . --exec dos2unix ${{ env.bashEnd }}"
+        fdfind --type=file ${args} . --exec dos2unix -q
 
-          # Determine if there was a formatting diff.
-          # If there was, create a patch of it.
-          set +e
-          git diff --exit-code >> formattingChanges.patch
-          exitCode=$?
-          set -e
+        # Determine if there was a formatting diff.
+        # If there was, create a patch of it.
+        set +e
+        git diff --exit-code >> formattingChanges.patch
+        exitCode=$?
+        set -e
 
-          if [ $exitCode -eq 0 ]; then
-              echo -e "::endgroup::"
-              echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          else
-              # Run a git diff to print the formatting differences
-              echo -e "::group::${{ env.bashInfo }} Format Difference ${{ env.bashEnd }}"
-              git diff --color=always
-              echo -e "::endgroup::${{ env.bashFail }} List of files with formatting errors: ${{ env.bashEnd }}"
-              echo -e "${{ env.bashFail }} "$(git diff --name-only)" ${{ env.bashEnd }} "
-              echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          fi
-          exit $exitCode
+        if [ $exitCode -eq 0 ]; then
+            echo -e "::endgroup::"
+            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        else
+            # Run a git diff to print the formatting differences
+            echo -e "::group::${{ env.bashInfo }} Format Difference ${{ env.bashEnd }}"
+            git diff --color=always
+            echo -e "::endgroup::${{ env.bashFail }} List of files with formatting errors: ${{ env.bashEnd }}"
+            echo -e "${{ env.bashFail }} "$(git diff --name-only)" ${{ env.bashEnd }} "
+            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        fi
+        exit $exitCode
 
-      - name: Upload Formatting Git Patch
-        if: failure() && ( steps.action-formatting-check.outcome == 'failure' )
-        id: upload-formatting-patch
-        uses: actions/upload-artifact@v3
-        with:
-          name: formattingChanges
-          path: ${{ inputs.path }}/formattingChanges.patch
-          retention-days: 7
+    - name: Upload Formatting Git Patch
+      if: failure() && ( steps.action-formatting-check.outcome == 'failure' )
+      id: upload-formatting-patch
+      uses: actions/upload-artifact@v3
+      with:
+        name: formattingChanges
+        path: ${{ inputs.path }}/formattingChanges.patch
+        retention-days: 7
 
-      - env:
-          stepName: Formatting Git Patch Info
-          bashPass: \033[32;1m
-          bashInfo: \033[33;1m
-          bashFail: \033[31;1m
-          bashEnd:  \033[0
-        if: failure() && ( steps.upload-formatting-patch.outcome == 'success' )
-        shell: bash
-        run: |
-          # ${{ env.stepName }}
-          echo -e "${{ env.bashInfo }} A git patch of the formatting issues has been attached to this workflow ${{ env.bashEnd }}"
-          echo -e "${{ env.bashInfo }} This can be accessed by returning to the bottom of the summary page of the workflow run ${{ env.bashEnd }}"
-          echo -e "${{ env.bashInfo }} At the bottom of the page will be a formattingChanges.patch file that you can download ${{ env.bashEnd }}"
-          echo -e "${{ env.bashInfo }} Copy this patch to your repository and apply it using 'git apply formattingChanges.patch' ${{ env.bashEnd }}"
+    - env:
+        stepName: Formatting Git Patch Info
+        bashPass: \033[32;1m
+        bashInfo: \033[33;1m
+        bashFail: \033[31;1m
+        bashEnd:  \033[0
+      if: failure() && ( steps.upload-formatting-patch.outcome == 'success' )
+      shell: bash
+      run: |
+        # ${{ env.stepName }}
+        echo -e "${{ env.bashInfo }} A git patch of the formatting issues has been attached to this workflow ${{ env.bashEnd }}"
+        echo -e "${{ env.bashInfo }} This can be accessed by returning to the bottom of the summary page of the workflow run ${{ env.bashEnd }}"
+        echo -e "${{ env.bashInfo }} At the bottom of the page will be a formattingChanges.zip file that you can download. ${{ env.bashEnd }}"
+        echo -e "${{ env.bashInfo }} Extract the 'formattingChanges.patch' file inside of it, and copy it to your repository. ${{ env.bashEnd }}"
+        echo -e "${{ env.bashInfo }} From here you can apply it using 'git apply formattingChanges.patch', fixing your formatting issues. ${{ env.bashEnd }}"
diff --git a/executable-monitor/action.yml b/executable-monitor/action.yml
--- a/executable-monitor/action.yml
+++ b/executable-monitor/action.yml
@@ -25,83 +25,83 @@ inputs:
 runs:
   using: "composite"
   steps:
-      - env:
-          # The bash escape character is \033
-          # At time of writing, you can't add a global environment to an
-          # action so stuck with this. If this gets changed please move this
-          bashPass:   \033[32;1mPASSED -
-          bashInfo:   \033[33;1mINFO -
-          bashFail:   \033[31;1mFAILED -
-          bashEnd:    \033[0m
-          stepName: Install Dependencies
-        name: ${{ env.stepName }}
-        shell: bash
-        run: |
-          # ${{ env.stepName }}
-          echo -e "::group::Install Dependencies"
-          pip install -r $GITHUB_ACTION_PATH/requirements.txt
-          exitStatus=$?
-          echo -e "::endgroup::"
+    - env:
+        # The bash escape character is \033
+        # At time of writing, you can't add a global environment to an
+        # action so stuck with this. If this gets changed please move this
+        bashPass:   \033[32;1mPASSED -
+        bashInfo:   \033[33;1mINFO -
+        bashFail:   \033[31;1mFAILED -
+        bashEnd:    \033[0m
+        stepName: Install Dependencies
+      name: ${{ env.stepName }}
+      shell: bash
+      run: |
+        # ${{ env.stepName }}
+        echo -e "::group::Install Dependencies"
+        pip install -r $GITHUB_ACTION_PATH/requirements.txt
+        exitStatus=$?
+        echo -e "::endgroup::"
+        echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+
+    - env:
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0m
+        stepName: Run Executable with Monitoring
+      name: ${{ env.stepName }}
+      shell: bash
+      run: |
+        # Run Executable with Monitoring
+        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+
+        # Make sure we have an exit condition to look for
+        if [ "${{ inputs.success-exit-code }}" = "" ] && [ "${{ inputs.success-line }}" = "" ]; then
+          echo -e "::endgroup::\n${{ env.bashFail}} Did not supply an input of success-line or success-exit-code to search for ${{ env.bashEnd }}"
+          exit 1
+        fi
+
+        # Initial Arguments
+        args="$GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }}"
+        args+=" --timeout-seconds=${{ inputs.timeout-seconds }}"
+
+        # Check if an exit code was provided
+        if [ -n "${{ inputs.success-exit-code }}" ]; then
+          args+=" --success-exit-code=${{ inputs.success-exit-code }}"
+        fi
+
+        # Check for log directory/if a log file should be created
+        if [ -n "${{ inputs.log-dir }}" ]; then
+          args+=" --log-dir=${{ inputs.log-dir}}"
+        fi
+
+        # Check for retry attempts
+        if [ -n "${{ inputs.retry-attempts }}" ]; then
+          args+=" --retry-attempts=${{ inputs.retry-attempts }}"
+        fi
+
+
+        # set +e so if the run fails we can capture that and print custom error message
+        set +e
+
+        # Check for success line to search for
+        if [ -n "${{ inputs.success-line }}" ]; then
+          echo -e "${{ env.bashInfo }} Running: python3 ${args} --success-line=${{ inputs.success-line}} ${{ env.bashEnd }}"
+          python3 ${args} --success-line="${{ inputs.success-line}}"
+        else
+          echo -e "${{ env.bashInfo }} Running: python3 ${args} ${{ env.bashEnd }}"
+          python3 ${args}
+        fi
+
+        # Store status as the echo group will overwrite it
+        exitStatus=$?
+        set -e
+        echo -e "::endgroup::"
+
+        if [ $exitStatus -eq 0 ]; then
           echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-
-      - env:
-          bashPass: \033[32;1mPASSED -
-          bashInfo: \033[33;1mINFO -
-          bashFail: \033[31;1mFAILED -
-          bashEnd:  \033[0m
-          stepName: Run Executable with Monitoring
-        name: ${{ env.stepName }}
-        shell: bash
-        run: |
-          # Run Executable with Monitoring
-          echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
-
-          # Make sure we have an exit condition to look for
-          if [ "${{ inputs.success-exit-code }}" = "" ] && [ "${{ inputs.success-line }}" = "" ]; then
-            echo -e "::endgroup::\n${{ env.bashFail}} Did not supply an input of success-line or success-exit-code to search for ${{ env.bashEnd }}"
-            exit 1
-          fi
-
-          # Initial Arguments
-          args="$GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }}"
-          args+=" --timeout-seconds=${{ inputs.timeout-seconds }}"
-
-          # Check if an exit code was provided
-          if [ -n "${{ inputs.success-exit-code }}" ]; then
-            args+=" --success-exit-code=${{ inputs.success-exit-code }}"
-          fi
-
-          # Check for log directory/if a log file should be created
-          if [ -n "${{ inputs.log-dir }}" ]; then
-            args+=" --log-dir=${{ inputs.log-dir}}"
-          fi
-
-          # Check for retry attempts
-          if [ -n "${{ inputs.retry-attempts }}" ]; then
-            args+=" --retry-attempts=${{ inputs.retry-attempts }}"
-          fi
-
-
-          # set +e so if the run fails we can capture that and print custom error message
-          set +e
-
-          # Check for success line to search for
-          if [ -n "${{ inputs.success-line }}" ]; then
-            echo -e "${{ env.bashInfo }} Running: python3 ${args} --success-line=${{ inputs.success-line}} ${{ env.bashEnd }}"
-            python3 ${args} --success-line="${{ inputs.success-line}}"
-          else
-            echo -e "${{ env.bashInfo }} Running: python3 ${args} ${{ env.bashEnd }}"
-            python3 ${args}
-          fi
-
-          # Store status as the echo group will overwrite it
-          exitStatus=$?
-          set -e
-          echo -e "::endgroup::"
-
-          if [ $exitStatus -eq 0 ]; then
-            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          else
-            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          fi
-          exit $exitStatus
+        else
+          echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        fi
+        exit $exitStatus
diff --git a/link-verifier/action.yml b/link-verifier/action.yml
--- a/link-verifier/action.yml
+++ b/link-verifier/action.yml
@@ -27,97 +27,97 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Setup Python for link verifier action
-      uses: actions/setup-python@v3
+  - name: Setup Python for link verifier action
+    uses: actions/setup-python@v3
 
-    - env:
-        # The bash escape character is \033
-        # At time of writing, you can't add a global environment
-        # to an action file. If this gets changed please move this
-        bashPass:   \033[32;1mPASSED -
-        bashInfo:   \033[33;1mINFO -
-        bashFail:   \033[31;1mFAILED -
-        bashEnd:    \033[0m
-        stepName: Install Dependencies
-      name: ${{ env.stepName }}
-      shell: bash
-      run: |
-        # ${{ env.stepName }}
-        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+  - env:
+      # The bash escape character is \033
+      # At time of writing, you can't add a global environment
+      # to an action file. If this gets changed please move this
+      bashPass:   \033[32;1mPASSED -
+      bashInfo:   \033[33;1mINFO -
+      bashFail:   \033[31;1mFAILED -
+      bashEnd:    \033[0m
+      stepName: Install Dependencies
+    name: ${{ env.stepName }}
+    shell: bash
+    run: |
+      # ${{ env.stepName }}
+      echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
 
-        wget https://github.com/jgm/pandoc/releases/download/2.11/pandoc-2.11-1-amd64.deb -O pandoc.deb
-        sudo dpkg -i pandoc.deb
+      wget https://github.com/jgm/pandoc/releases/download/2.11/pandoc-2.11-1-amd64.deb -O pandoc.deb
+      sudo dpkg -i pandoc.deb
 
-        rm pandoc.deb
-        sudo apt install debsums
+      rm pandoc.deb
+      sudo apt install debsums
 
-        sudo debsums pandoc
-        sudo type -p curl >/dev/null || sudo apt install curl -y
-        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
-        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
-        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
+      sudo debsums pandoc
+      sudo type -p curl >/dev/null || sudo apt install curl -y
+      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
+      sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
+      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
 
-        sudo apt update
-        sudo apt install -y gh
-        sudo apt install pandoc -y
-        sudo apt-get install -y python3-setuptools python3-pip
+      sudo apt update
+      sudo apt install -y gh
+      sudo apt install pandoc -y
+      sudo apt-get install -y python3-setuptools python3-pip
 
-        python3 -m pip install -r  $GITHUB_ACTION_PATH/requirements.txt
+      python3 -m pip install -r  $GITHUB_ACTION_PATH/requirements.txt
 
-        echo -e "::endgroup::"
-        echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd}}"
+      echo -e "::endgroup::"
+      echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd}}"
 
-    - env:
-        bashPass: \033[32;1mPASSED -
-        bashInfo: \033[33;1mINFO -
-        bashFail: \033[31;1mFAILED -
-        bashEnd:  \033[0m
-        stepName: Check Links in Files
-      name: ${{ env.stepName }}
-      working-directory: ${{ inputs.path }}
-      shell: bash
-      run: |
-        # ${{ env.stepName }}
-        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
-        args="--test-markdown"
-        if [ -n "${{ inputs.exclude-dirs }}" ]; then
-          dirs="${{ inputs.exclude-dirs }}"
-          dirs="${dirs//,/ }"
-          args+=" --exclude-dirs ${dirs}"
-        fi
+  - env:
+      bashPass: \033[32;1mPASSED -
+      bashInfo: \033[33;1mINFO -
+      bashFail: \033[31;1mFAILED -
+      bashEnd:  \033[0m
+      stepName: Check Links in Files
+    name: ${{ env.stepName }}
+    working-directory: ${{ inputs.path }}
+    shell: bash
+    run: |
+      # ${{ env.stepName }}
+      echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+      args="--test-markdown"
+      if [ -n "${{ inputs.exclude-dirs }}" ]; then
+        dirs="${{ inputs.exclude-dirs }}"
+        dirs="${dirs//,/ }"
+        args+=" --exclude-dirs ${dirs}"
+      fi
 
-        if [ -n "${{ inputs.include-file-types }}" ]; then
-          file_types="${{ inputs.include-file-types }}"
-          file_types="${file_types//,/ }"
-          args+=" --include-file-types ${file_types}"
-        fi
+      if [ -n "${{ inputs.include-file-types }}" ]; then
+        file_types="${{ inputs.include-file-types }}"
+        file_types="${file_types//,/ }"
+        args+=" --include-file-types ${file_types}"
+      fi
 
-        if [ -n "${{ inputs.allowlist-file }}" ]; then
-          touch allowList.txt
-          cat ${{ inputs.allowlist-file }} >> allowList.txt
-        fi
+      if [ -n "${{ inputs.allowlist-file }}" ]; then
+        touch allowList.txt
+        cat ${{ inputs.allowlist-file }} >> allowList.txt
+      fi
 
-        if [[ "${{ inputs.exclude-urls }}" != "" ]]; then
-          touch allowList.txt
-          exclude_urls="${{ inputs.exclude-urls }}"
-          exclude_urls="${exclude_urls//,/ }"
-          for url in ${exclude_urls[@]}; do echo -e "$url" >> allowList.txt; done
-        fi
+      if [[ "${{ inputs.exclude-urls }}" != "" ]]; then
+        touch allowList.txt
+        exclude_urls="${{ inputs.exclude-urls }}"
+        exclude_urls="${exclude_urls//,/ }"
+        for url in ${exclude_urls[@]}; do echo -e "$url" >> allowList.txt; done
+      fi
 
-        if [ -n "${{ inputs.allowlist-file }}" ] || [ -n "${{ inputs.exclude-urls }}" ]; then
-          args+=" --allowlist-file allowList.txt"
-        fi
+      if [ -n "${{ inputs.allowlist-file }}" ] || [ -n "${{ inputs.exclude-urls }}" ]; then
+        args+=" --allowlist-file allowList.txt"
+      fi
 
-        echo -e "${{ env.bashInfo }} Running: verify-links.py ${args} --user-agent \"${{ inputs.user-agent }}\" ${{ env.bashEnd }}"
-        set +e
-        python3 ${GITHUB_ACTION_PATH}/verify-links.py ${args} --user-agent "${{ inputs.user-agent }}";
-        exitStatus=$?
-        set -e
+      echo -e "${{ env.bashInfo }} Running: verify-links.py ${args} --user-agent \"${{ inputs.user-agent }}\" ${{ env.bashEnd }}"
+      set +e
+      python3 ${GITHUB_ACTION_PATH}/verify-links.py ${args} --user-agent "${{ inputs.user-agent }}";
+      exitStatus=$?
+      set -e
 
-        echo -e "::endgroup::"
-        if [ $exitStatus -eq 1 ]; then
-          echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-        else
-          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-        fi
-        exit $exitStatus
+      echo -e "::endgroup::"
+      if [ $exitStatus -eq 1 ]; then
+        echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+      else
+        echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+      fi
+      exit $exitStatus
diff --git a/manifest-verifier/action.yml b/manifest-verifier/action.yml
--- a/manifest-verifier/action.yml
+++ b/manifest-verifier/action.yml
@@ -16,49 +16,49 @@ inputs:
 runs:
   using: "composite"
   steps:
-      - env:
-          bashPass: \033[32;1mPASSED -
-          bashInfo: \033[33;1mINFO -
-          bashFail: \033[31;1mFAILED -
-          bashEnd:  \033[0m
-          stepName: Install Manifest Verification Dependencies
-        name: ${{ env.stepName }}
-        shell: bash
-        run: |
-          # ${{ env.stepName }}
-          echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          pip install -r $GITHUB_ACTION_PATH/requirements.txt
-          exitStatus=$?
-          echo -e "::endgroup::"
+    - env:
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0m
+        stepName: Install Manifest Verification Dependencies
+      name: ${{ env.stepName }}
+      shell: bash
+      run: |
+        # ${{ env.stepName }}
+        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        pip install -r $GITHUB_ACTION_PATH/requirements.txt
+        exitStatus=$?
+        echo -e "::endgroup::"
+        echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+
+    - env:
+        bashPass: \033[32;1mPASSED -
+        bashInfo: \033[33;1mINFO -
+        bashFail: \033[31;1mFAILED -
+        bashEnd:  \033[0m
+        stepName: Run Manifest Verification Script
+      name: ${{ env.stepName }}
+      working-directory: ${{ inputs.path }}
+      shell: bash
+      run: |
+        # ${{ env.stepName }}
+        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+
+        if [[ "${{ inputs.fail-on-incorrect-version }}" == "true" ]]; then
+          echo -e "${{ env.bashInfo}} Value of flag is ${{ inputs.fail-on-incorrect-version }} ${{ env.bashEnd }}"
+          echo -e "${{ env.bashInfo}} Running: python3 manifest-verifier.py --ignore-submodule-path=${{ inputs.exclude-submodules }} --fail-on-incorrect-version ${{ inputs.fail-on-incorrect-version }} ${{ env.bashEnd }}"
+          python3 $GITHUB_ACTION_PATH/manifest-verifier.py  --ignore-submodule-path=${{ inputs.exclude-submodules }} --fail-on-incorrect-version
+        else
+          echo -e "${{ env.bashInfo}} Running: python3 manifest-verifier.py --ignore-submodule-path=${{ inputs.exclude-submodules }} ${{ env.bashEnd }}"
+          python3 $GITHUB_ACTION_PATH/manifest-verifier.py  --ignore-submodule-path=${{ inputs.exclude-submodules }}
+        fi
+        exitStatus=$?
+
+        echo -e "::endgroup::"
+        if [ "$exitStatus" = "0" ]; then
           echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-
-      - env:
-          bashPass: \033[32;1mPASSED -
-          bashInfo: \033[33;1mINFO -
-          bashFail: \033[31;1mFAILED -
-          bashEnd:  \033[0m
-          stepName: Run Manifest Verification Script
-        name: ${{ env.stepName }}
-        working-directory: ${{ inputs.path }}
-        shell: bash
-        run: |
-          # ${{ env.stepName }}
-          echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
-
-          if [[ "${{ inputs.fail-on-incorrect-version }}" == "true" ]]; then
-            echo -e "${{ env.bashInfo}} Value of flag is ${{ inputs.fail-on-incorrect-version }} ${{ env.bashEnd }}"
-            echo -e "${{ env.bashInfo}} Running: python3 manifest-verifier.py --ignore-submodule-path=${{ inputs.exclude-submodules }} --fail-on-incorrect-version ${{ inputs.fail-on-incorrect-version }} ${{ env.bashEnd }}"
-            python3 $GITHUB_ACTION_PATH/manifest-verifier.py  --ignore-submodule-path=${{ inputs.exclude-submodules }} --fail-on-incorrect-version
-          else
-            echo -e "${{ env.bashInfo}} Running: python3 manifest-verifier.py --ignore-submodule-path=${{ inputs.exclude-submodules }} ${{ env.bashEnd }}"
-            python3 $GITHUB_ACTION_PATH/manifest-verifier.py  --ignore-submodule-path=${{ inputs.exclude-submodules }}
-          fi
-          exitStatus=$?
-
-          echo -e "::endgroup::"
-          if [ "$exitStatus" = "0" ]; then
-            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          else
-            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-            exit 1
-          fi
+        else
+          echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          exit 1
+        fi
diff --git a/spellings/action.yml b/spellings/action.yml
--- a/spellings/action.yml
+++ b/spellings/action.yml
@@ -19,105 +19,105 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - env:
-        bashPass: \033[32;1mPASSED -
-        bashInfo: \033[33;1mINFO -
-        bashFail: \033[31;1mFAILED -
-        bashEnd:  \033[0m
-        stepName: Set-Up The Spell Checker
-      name: ${{ env.stepName }}
-      id: spell-checker-setup
-      shell: bash
-      run: |
-        # ${{ env.stepName }}
-        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+  - env:
+      bashPass: \033[32;1mPASSED -
+      bashInfo: \033[33;1mINFO -
+      bashFail: \033[31;1mFAILED -
+      bashEnd:  \033[0m
+      stepName: Set-Up The Spell Checker
+    name: ${{ env.stepName }}
+    id: spell-checker-setup
+    shell: bash
+    run: |
+      # ${{ env.stepName }}
+      echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
 
-        # Install the Dependencies we need to run the spell-checker
-        sudo apt-get install util-linux -y
-        sudo apt-get install fd-find -y
-        sudo apt-get install npm -y
-        sudo npm install -g cspell
+      # Install the Dependencies we need to run the spell-checker
+      sudo apt-get install util-linux -y
+      sudo apt-get install fd-find -y
+      sudo apt-get install npm -y
+      sudo npm install -g cspell
 
-        # Add the Github Action Path to PATH
-        export PATH="$GITHUB_ACTION_PATH:$PATH"
+      # Add the Github Action Path to PATH
+      export PATH="$GITHUB_ACTION_PATH:$PATH"
 
-        # Account for starting with an alternate path in a repository
-        # Do this by copying the cspell config and wordlist to the desired path
-        # Wrap in a set +e so Github doesn't throw an error if the file or
-        # directory already exists.
-        set +e
-        cp cspell.config.yaml ${{ inputs.path }}
-        mkdir ${{ inputs.path }}/.github
-        cp .github/.cSpellWords.txt ${{ inputs.path }}/.github
-        cd ${{ inputs.path }}
-        set -e
+      # Account for starting with an alternate path in a repository
+      # Do this by copying the cspell config and wordlist to the desired path
+      # Wrap in a set +e so Github doesn't throw an error if the file or
+      # directory already exists.
+      set +e
+      cp cspell.config.yaml ${{ inputs.path }}
+      mkdir ${{ inputs.path }}/.github
+      cp .github/.cSpellWords.txt ${{ inputs.path }}/.github
+      cd ${{ inputs.path }}
+      set -e
 
-        echo -e "::endgroup::"
-        # Make sure we have all the commands we need.
-        echo -e "${{ env.bashInfo }} fdfind --version $(fdfind --version) ${{ env.bashEnd }}"
-        echo -e "${{ env.bashInfo }} cspell --version $(cspell --version) ${{ env.bashEnd }}"
+      echo -e "::endgroup::"
+      # Make sure we have all the commands we need.
+      echo -e "${{ env.bashInfo }} fdfind --version $(fdfind --version) ${{ env.bashEnd }}"
+      echo -e "${{ env.bashInfo }} cspell --version $(cspell --version) ${{ env.bashEnd }}"
 
-        # Only reach this line if no errors were hit above
+      # Only reach this line if no errors were hit above
+      echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+
+  - env:
+      bashPass: \033[32;1mPASSED -
+      bashInfo: \033[33;1mINFO -
+      bashFail: \033[31;1mFAILED -
+      bashEnd:  \033[0m
+      stepName: Spell Checker
+    name: ${{ env.stepName }}
+    id: run-spell-checker
+    working-directory: ${{ inputs.path }}
+    shell: bash
+    run: |
+      # ${{ env.stepName }}
+      echo -e "::group:${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+      export PATH="$GITHUB_ACTION_PATH:$PATH"
+      exitStatus=0
+
+      # Parse the optional inputs
+      args=""
+
+      # fd-find uses -E to exclude a file or directory
+      if [ -n "${{ inputs.exclude-dirs }}" ]; then
+        dirs=" -E "
+        dirs+="${{ inputs.exclude-dirs }}"
+        dirs="${dirs//,/ -E }"
+        args+=" ${dirs}"
+      fi
+
+      # fd-find uses -E to exclude a file or directory
+      if [ -n "${{ inputs.exclude-files }}" ]; then
+        files=" -E "
+        files+="${{ inputs.exclude-files }}"
+        files="${files//,/ -E }"
+        args+=" ${files}"
+      fi
+
+      # fd-find uses -e to exclude a file extension
+      if [ -n "${{ inputs.include-file-types }}" ]; then
+        file_types=" -e "
+        file_types+="${{ inputs.include-file-types }}"
+        file_types="${file_types//,/ -e }"
+        args+=" ${file_types}"
+      fi
+
+      echo -e "${{ env.bashInfo }} Running: fdfind -e c -e h -e md -e txt -e readme ${args} --exec cspell lint --language-id C --color --show-context --show-suggestions --no-must-find-files -c cspell.config.yaml ${{ env.bashEnd }}"
+
+      # Wrap in a set +e so Github doesn't stop the spell check from running
+      set +e
+
+      # Find all relevant files, then check them for spelling mistakes
+      fdfind -e c -e h -e md -e txt -e readme ${args} --exec-batch \
+        cspell lint --language-id C --color --show-context --show-suggestions --no-must-find-files -c cspell.config.yaml
+      exitStatus=$?
+      set -e
+
+      echo -e "::endgroup::"
+      if [ $exitStatus -eq 0 ]; then
         echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-
-    - env:
-        bashPass: \033[32;1mPASSED -
-        bashInfo: \033[33;1mINFO -
-        bashFail: \033[31;1mFAILED -
-        bashEnd:  \033[0m
-        stepName: Spell Checker
-      name: ${{ env.stepName }}
-      id: run-spell-checker
-      working-directory: ${{ inputs.path }}
-      shell: bash
-      run: |
-        # ${{ env.stepName }}
-        echo -e "::group:${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
-        export PATH="$GITHUB_ACTION_PATH:$PATH"
-        exitStatus=0
-
-        # Parse the optional inputs
-        args=""
-
-        # fd-find uses -E to exclude a file or directory
-        if [ -n "${{ inputs.exclude-dirs }}" ]; then
-          dirs=" -E "
-          dirs+="${{ inputs.exclude-dirs }}"
-          dirs="${dirs//,/ -E }"
-          args+=" ${dirs}"
-        fi
-
-        # fd-find uses -E to exclude a file or directory
-        if [ -n "${{ inputs.exclude-files }}" ]; then
-          files=" -E "
-          files+="${{ inputs.exclude-files }}"
-          files="${files//,/ -E }"
-          args+=" ${files}"
-        fi
-
-        # fd-find uses -e to exclude a file extension
-        if [ -n "${{ inputs.include-file-types }}" ]; then
-          file_types=" -e "
-          file_types+="${{ inputs.include-file-types }}"
-          file_types="${file_types//,/ -e }"
-          args+=" ${file_types}"
-        fi
-
-        echo -e "${{ env.bashInfo }} Running: fdfind -e c -e h -e md -e txt -e readme ${args} --exec cspell lint --language-id C --color --show-context --show-suggestions --no-must-find-files -c cspell.config.yaml ${{ env.bashEnd }}"
-
-        # Wrap in a set +e so Github doesn't stop the spell check from running
-        set +e
-
-        # Find all relevant files, then check them for spelling mistakes
-        fdfind -e c -e h -e md -e txt -e readme ${args} --exec-batch \
-          cspell lint --language-id C --color --show-context --show-suggestions --no-must-find-files -c cspell.config.yaml
-        exitStatus=$?
-        set -e
-
-        echo -e "::endgroup::"
-        if [ $exitStatus -eq 0 ]; then
-          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-        else
-          echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-        fi
-        exit $exitStatus
+      else
+        echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+      fi
+      exit $exitStatus
