Updating getFiles to kinda work for FreeBSD

diff --git a/spellings/getFiles b/spellings/getFiles
--- a/spellings/getFiles
+++ b/spellings/getFiles
@@ -4,76 +4,114 @@ bashInfo="\033[33;1mINFO -"
 bashFail="\033[31;1mFAILED -"
 bashEnd="\033[0m"
 
-output=$(getopt -V)
-if [[ *"getopt"* == "$output" ]] && [ $# != 0 ]; then
-    echo -e "$bashInfo This script cannot parse options from Mac command line's default 'getopt' $bashEnd"
-    echo -e "$bashInfo Run \"brew install gnu-getopt\" and then add it to your path using $bashEnd"
-    echo -e "$bashInfo export PATH=\"/opt/homebrew/opt/gnu-getopt/bin:\$PATH\" $bashEnd"
-    echo -e "$bashInfo At which point you can then use this script with options $bashEnd"
-    exit 1;
-fi
 # Check number of arguments
 files=""
 file=""
 excludeDirs=""
 excludeFiles=""
 includeExtensions=""
-if [ $# != 0 ]; then
+
+# Check if we're using gnu getopt or FreeBSD getopt
+output=$(getopt -V)
+if [[ *"getopt"* == "$output" ]]; then
     VALID_ARGS=$(getopt -o h,ed:,ef:,if: --long help,exclude-dirs:,exclude-files:,include-extensions: -- "$@")
     eval set -- "$VALID_ARGS"
-    while [ : ]; do
-        case "$1" in
-            ed | --exclude-dirs )
-                # $2 Holds the argument passed after --exclude-files or --ed
-                # Use sed to replace the commas with the exclude flag
-                if ! [ -z "$2" ]; then
-                    excludeDirs="-E $(echo "$2" | sed -r 's/,/ -E /g' )"
-                fi
-                shift 2
-                ;;
+    if [ $# != 0 ]; then
+        while [ : ]; do
+            case "$1" in
+                ed | --exclude-dirs )
+                    # $2 Holds the argument passed after --exclude-files or --ed
+                    # Use sed to replace the commas with the exclude flag
+                    if ! [ -z "$2" ]; then
+                        excludeDirs="-E $(echo "$2" | sed -r 's/,/ -E /g' )"
+                    fi
+                    shift 2
+                    ;;
 
-            ef | --exclude-files )
-                # $2 Holds the argument passed after --exclude-files or --ed
-                # Use sed to replace the commas with the exclude flag
-                if ! [ -z "$2" ]; then
-                    excludeFiles="-E $( echo "$2" | sed -r 's/,/ -E /g' )"
-                fi
-                shift 2
-                ;;
+                ef | --exclude-files )
+                    # $2 Holds the argument passed after --exclude-files or --ed
+                    # Use sed to replace the commas with the exclude flag
+                    if ! [ -z "$2" ]; then
+                        excludeFiles="-E $( echo "$2" | sed -r 's/,/ -E /g' )"
+                    fi
+                    shift 2
+                    ;;
 
-            if | --include-extensions )
-                # $2 Holds the argument passed after --exclude-files or --ed
-                # Use sed to replace the commas with the exclude flag
-                if ! [ -z "$2" ]; then
-                    includeExtensions="-e $( echo "$2" | sed -r 's/,/ -E /g' )"
-                fi
-                shift 2
-                ;;
+                if | --include-extensions )
+                    # $2 Holds the argument passed after --exclude-files or --ed
+                    # Use sed to replace the commas with the exclude flag
+                    if ! [ -z "$2" ]; then
+                        includeExtensions="-e $( echo "$2" | sed -r 's/,/ -E /g' )"
+                    fi
+                    shift 2
+                    ;;
 
-            h | --help )
+                h | --help )
+                    echo -e "$bashInfo Find all .c and .h files with the Amazon copyright in them $bashEnd"
+                    echo -e "$bashInfo It exports this to a bash array variable called \"files\" $bashEnd"
+                    echo -e "$bashInfo This script can take in two optional arguments $bashEnd"
+                    echo -e "$bashInfo --exclude-files:       A comma seperated list of files to exclude $bashEnd"
+                    echo -e "$bashInfo --exclude-dir:         A comma seperated list of directories to exclude $bashEnd"
+                    echo -e "$bashInfo --include-extensions:  Any additional exstensions to search for $bashEnd"
+                    exit 0
+                    ;;
+                -- )
+                    shift
+                    break
+                    ;;
+                esac
+        done
+    fi
+    # Make the assumption that gnu getopt means you're going to use fdfind vs fd
+    # By default only grab the c and h files. Only grab the files with amazon copyright
+    # Put all the files in an array. Uncomment the following line to see the command run.
+    # echo "fdfind -e c -e h "$excludeDirs" "$excludeFiles" "$includeExtensions" --exec grep -lriE \"copyright (.*) 20[0-9]{2} amazon.com\" "
+    files=$(fdfind -e c -e h $excludeDirs $excludeFiles $includeExtensions --exec grep -lriE "copyright (.*) 20[0-9]{2} amazon.com" )
+
+else
+    while [ $# -gt 0 ]; do
+    case "$1" in
+        -ed= | --exclude-dirs=* )
+            excludeDirs="-E $(echo "${1#*=}" | sed -E 's/,/ -E /g')"
+            shift
+            ;;
+        -ef= | --exclude-files=* )
+            excludeFiles="-E $(echo "${1#*=}" | sed -E 's/,/ -E /g')"
+            shift
+            ;;
+        -ie= | --include-extensions* )
+            includeExtensions="-e $(echo "${1#*=}" | sed -E 's/,/ -e /g')"
+            shift
+            ;;
+        -h | --help )
                 echo -e "$bashInfo Find all .c and .h files with the Amazon copyright in them $bashEnd"
                 echo -e "$bashInfo It exports this to a bash array variable called \"files\" $bashEnd"
                 echo -e "$bashInfo This script can take in two optional arguments $bashEnd"
-                echo -e "$bashInfo --exclude-files:       A comma seperated list of files to exclude $bashEnd"
-                echo -e "$bashInfo --exclude-dir:         A comma seperated list of directories to exclude $bashEnd"
-                echo -e "$bashInfo --include-extensions:  Any additional exstensions to search for $bashEnd"
+                echo -e "$bashInfo -ef= | --exclude-files=:       A comma seperated list of files to exclude $bashEnd"
+                echo -e "$bashInfo -ed= | --exclude-dir=:         A comma seperated list of directories to exclude $bashEnd"
+                echo -e "$bashInfo -ie= | --include-extensions=:  Any additional exstensions to search for $bashEnd"
                 exit 0
-                ;;
-            -- )
-                shift
-                break
-                ;;
-            esac
+            ;;
+        *)
+            echo "Unknown option: $1"
+            exit 1
+            ;;
+        esac
     done
+# For FreeBSD (default MacOS shell) assume that you have fd
+# By default only grab the c and h files. Only grab the files with amazon copyright
+# Put all the files in an array. Uncomment the following line to see the command run.
+# echo "fd -e c -e h "$excludeDirs" "$excludeFiles" "$includeExtensions" --exec grep -lriE \"copyright (.*) 20[0-9]{2} amazon.com\" "
+files=$(fd -e c -e h $excludeDirs $excludeFiles $includeExtensions --exec grep -lrie "copyright (.*) 20\d\d amazon.com")
+echo "files=$files"
 fi
 
-# We know we just want the .c and .h files
-# It's just way easier to do this then it is to write
-# A complicated thing to handle parsing the arguments
-#echo "Hello"
-#echo "fdfind -e c -e h "$excludeDirs" "$excludeFiles" "$includeExtensions" --exec grep -lriE \"copyright (.*) [0-9]{4} amazon.com\" "
-files=$(fdfind -e c -e h $excludeDirs $excludeFiles $includeExtensions --exec grep -lriE "copyright (.*) [0-9]{4} amazon.com" )
-
+# For future FreeBSD users:
+# By default if you try and capture this output like you see on the github workflows
+# By doing something like files=$(getFiles <ARGS>) it will look like it doesn't work
+# This is because on a Mac's default shell this will expand to a single variable
+# But on ubuntu's default shell it will expand to an array that can be iterated over
+# My recommendation would be to uncomment the fd command above and capture that
 for file in ${files[@]}; do
     if ! [ -z "$file" ]; then
         echo "$file"
