Remove un-needed files, fix a difference in the MacOS getFiles scripts

diff --git a/spellings/getFiles b/spellings/getFiles
--- a/spellings/getFiles
+++ b/spellings/getFiles
@@ -23,7 +23,7 @@ if [[ "$OSTYPE" == "darwin"* ]]; then
             excludeFiles="-E $(echo "${1#*=}" | sed -E 's/,/ -E /g')"
             shift
             ;;
-        -ie= | --include-extensions* )
+        -ie= | --include-extensions=* )
             includeExtensions="-e $(echo "${1#*=}" | sed -E 's/,/ -e /g')"
             shift
             ;;
@@ -45,8 +45,11 @@ if [[ "$OSTYPE" == "darwin"* ]]; then
     # For FreeBSD (default MacOS shell) assume that you have fd
     # By default only grab the c and h files. Only grab the files with amazon copyright
     # Put all the files in an array. Uncomment the following line to see the command run.
-    # echo "fd -e c -e h "$excludeDirs" "$excludeFiles" "$includeExtensions" --exec grep -lriE \"copyright (.*) 20[0-9]{2} amazon.com\" "
-    files=$(fd -e c -e h $excludeDirs $excludeFiles $includeExtensions --exec grep -lrie "copyright (.*) 20\d\d amazon.com")
+    # echo "fd -e c -e h "$excludeDirs" "$excludeFiles" "$includeExtensions" --exec grep -lie \"copyright (.*) 20[0-9]{2} amazon.com\" "
+    # Need this in a set +/- e so it doesn't return an error on files that fail the grep
+    set +e
+    files=$(fd -e c -e h $excludeDirs $excludeFiles $includeExtensions --exec grep -lie "copyright (.*) 20\d\d amazon.com")
+    set -e
 
 # Making the assumption that anybody else running this is a gnu getopt user
 else
@@ -99,8 +102,11 @@ else
     # Make the assumption that gnu getopt means you're going to use fdfind vs fd
     # By default only grab the c and h files. Only grab the files with amazon copyright
     # Put all the files in an array. Uncomment the following line to see the command run.
-    # echo "fdfind -e c -e h "$excludeDirs" "$excludeFiles" "$includeExtensions" --exec grep -lriE \"copyright (.*) 20[0-9]{2} amazon.com\" "
-    files=$(fdfind -e c -e h $excludeDirs $excludeFiles $includeExtensions --exec grep -lriE "copyright (.*) 20[0-9]{2} amazon.com" )
+    # echo "fdfind -e c -e h "$excludeDirs" "$excludeFiles" "$includeExtensions" --exec grep -liE \"copyright (.*) 20[0-9]{2} amazon.com\" "
+    # Need this in a set +/- e so it doesn't return an error on files that fail the grep
+    set +e
+    files=$(fdfind -e c -e h $excludeDirs $excludeFiles $includeExtensions --exec grep -liE "copyright (.*) 20[0-9]{2} amazon.com" )
+    set -e
 fi
 
 # For future FreeBSD users:
