Think I fixed the bug that was causing the spell check to fail even if it didn't find mis-spelled words. Added in a failure test for it as well

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,4 @@
-name: Test actions
+name: Test Actions
 
 on:
   push:
@@ -87,6 +87,45 @@ jobs:
         with:
           path: coreMQTT
 
+  test-spell-checker-find-mistake:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/checkout@v3
+        with:
+          repository: skptak/coreMQTT
+          ref: main
+          path: coreMQTT
+
+      - name: Empty the lexicon
+        shell: bash
+        working-directory: coreMQTT
+        run: file=$(find . -name .cSpellWords.txt); readlink -f "$file" ; > "$file"
+
+      - name: Test Spell Check Fails on Misspelled Word
+        continue-on-error: true
+        id: test-spellings-find-mistake
+        uses: ./spellings
+        with:
+          path: coreMQTT
+
+      - env:
+          stepName: Check Failure Test Case
+        name: ${{ env.stepName }}
+        id: check-failure-test-cases
+        shell: bash
+        run: |
+          # ${{ env.stepName }}
+          exitStatus=0
+          if [ "${{ steps.test-spellings-find-mistake.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} Functional | Failure | Fail on Misspelled Word | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} Functional | Failure | Fail on Misspelled Word | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          exit $exitStatus
+
   test-rust-spell-check:
     runs-on: ubuntu-latest
     steps:
@@ -146,7 +185,7 @@ jobs:
 
       - name: Test Spell Check Fails on Misspelled Word
         continue-on-error: true
-        id: test-spell-check-find-mistake
+        id: test-rust-spell-check-find-mistake
         uses: ./rust-spell-check
         with:
           path: coreMQTT
@@ -159,7 +198,7 @@ jobs:
         run: |
           # ${{ env.stepName }}
           exitStatus=0
-          if [ "${{ steps.test-spell-check-find-mistake.outcome}}" = "failure" ]; then
+          if [ "${{ steps.test-rust-spell-check-find-mistake.outcome}}" = "failure" ]; then
             echo -e "${{ env.bashPass }} Functional | Failure | Fail on Misspelled Word | Had Expected "failure" ${{ env.bashEnd }}"
           else
             echo -e "${{ env.bashFail }} Functional | Failure | Fail on Misspelled Word | Had Unexpected "success" ${{ env.bashEnd }}"
