Update the spell check action to be faster, add in exclude dirs and files directly, update test to account for it, move the .cSpellWords.txt file to live in .github

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,6 +7,13 @@ on:
     branches: [main]
   workflow_dispatch:
 
+env:
+  # The bash escape character is \033
+  bashPass:   \033[32;1mPASSED -
+  bashInfo:   \033[33;1mINFO -
+  bashFail:   \033[31;1mFAILED -
+  bashEnd:    \033[0m
+
 jobs:
   test-format-check:
     runs-on: ubuntu-20.04
@@ -109,7 +116,7 @@ jobs:
           exe-path: executable-monitor/test.out
           success-line: "SLEEPING FOR 6 SECONDS"
           timeout-seconds: 20
-      
+
       - name: Functional Test | Success Case | No Retries, No Success Line, Exit Code
         id: test-executable-monitor-action-no-retry-attempts-exit-code
         uses: ./executable-monitor
@@ -125,7 +132,7 @@ jobs:
           exe-path: executable-monitor/test.out
           success-line: "SLEEPING FOR 6 SECONDS"
           retry-attempts: 2
-          
+
       - name: API Test | Success Case | Retries, No Success Line, Exit Code, Use Default Timeout
         id: test-executable-monitor-action-no-success-line-no-timeout
         uses: ./executable-monitor
@@ -269,16 +276,58 @@ jobs:
   test-spell-check:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
+
+      - uses: actions/checkout@v3
         with:
-          repository: FreeRTOS/coreMQTT
-          ref: main
+          repository: skptak/coreMQTT
+          ref: CI-CD-Updates
           path: coreMQTT
+
       - name: Test spell check action
         uses: ./spellings
         with:
           path: coreMQTT
+
+  test-spell-checker-find-mistake:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/checkout@v3
+        with:
+          repository: skptak/coreMQTT
+          ref: CI-CD-Updates
+          path: coreMQTT
+
+      - name: Empty the lexicon
+        shell: bash
+        working-directory: coreMQTT
+        run: file=$(find . -name .cSpellWords.txt); readlink -f "$file" ; > "$file"
+
+      - name: Test Spell Check Fails on Misspelled Word
+        continue-on-error: true
+        id: test-spellings-find-mistake
+        uses: ./spellings
+        with:
+          path: coreMQTT
+
+      - env:
+          stepName: Check Failure Test Case
+        name: ${{ env.stepName }}
+        id: check-failure-test-cases
+        shell: bash
+        run: |
+          # ${{ env.stepName }}
+          exitStatus=0
+          if [ "${{ steps.test-spellings-find-mistake.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} Functional | Failure | Fail on Misspelled Word | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} Functional | Failure | Fail on Misspelled Word | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          exit $exitStatus
+
   test-coverage-cop:
     runs-on: ubuntu-latest
     steps:
@@ -353,7 +402,7 @@ jobs:
           repository: FreeRTOS/FreeRTOS
           ref: '202107.00'
           path: FreeRTOS
-          submodules: recursive      
+          submodules: recursive
       - name: Test manifest verifier
         uses: ./manifest-verifier
         with:
