CSpell Action (#75)
* Update the spell check action to use cSpell, add in exclude dirs and files directly, update tests to account for it, move the .cSpellWords.txt file to live in .github
* Changes to the cspell action to account for running in a different directory, updating the config file as well

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -83,16 +83,57 @@ jobs:
   test-spell-check:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
+
+      - uses: actions/checkout@v3
         with:
-          repository: FreeRTOS/coreMQTT
-          ref: main
+          repository: skptak/coreMQTT
+          ref: CI-CD-Updates
           path: coreMQTT
+
       - name: Test spell check action
         uses: ./spellings
         with:
           path: coreMQTT
+
+  test-spell-checker-find-mistake:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/checkout@v3
+        with:
+          repository: skptak/coreMQTT
+          ref: CI-CD-Updates
+          path: coreMQTT
+
+      - name: Empty the lexicon
+        shell: bash
+        working-directory: coreMQTT
+        run: file=$(find . -name .cSpellWords.txt); readlink -f "$file" ; > "$file"
+
+      - name: Test Spell Check Fails on Misspelled Word
+        continue-on-error: true
+        id: test-spellings-find-mistake
+        uses: ./spellings
+        with:
+          path: coreMQTT
+
+      - env:
+          stepName: Check Failure Test Case
+        name: ${{ env.stepName }}
+        id: check-failure-test-cases
+        shell: bash
+        run: |
+          # ${{ env.stepName }}
+          exitStatus=0
+          if [ "${{ steps.test-spellings-find-mistake.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} Functional | Failure | Fail on Misspelled Word | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} Functional | Failure | Fail on Misspelled Word | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          exit $exitStatus
 
   test-coverage-cop:
     runs-on: ubuntu-latest
