Fixing various typos and the like

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -33,7 +33,8 @@ jobs:
 
   test-executable-monitor-success-cases:
     strategy:
-      matrix:
+      fail-fast: false
+      matrix: 
           os: [ubuntu-latest, windows-latest]
           inputs:
             [
@@ -43,7 +44,8 @@ jobs:
                 description: "Exit Code Found",
                 exe-path: executable-monitor/test.out,
                 success-exit-code: 0,
-                log-dir: logDirectory
+                log-dir: logDirectory,
+                timeout-seconds: 60,
               },
               {
                 test-type: Functional,
@@ -51,7 +53,8 @@ jobs:
                 description: "Success Line Found",
                 exe-path: executable-monitor/test.out,
                 success-line: "SLEEPING FOR 6 SECONDS",
-                log-dir: logDirectory
+                log-dir: logDirectory,
+                timeout-seconds: 30,
               },
               {
                 test-type: Functional,
@@ -60,6 +63,7 @@ jobs:
                 exe-path: executable-monitor/test.out,
                 success-line: "LINE_THAT_WILL_NOT_PRINT",
                 success-exit-code: 0,
+                timeout-seconds: 60,
               },
               {
                 test-type: Functional,
@@ -68,22 +72,25 @@ jobs:
                 exe-path: executable-monitor/test.out,
                 success-line: "SLEEPING FOR 6 SECONDS",
                 success-exit-code: 0,
+                timeout-seconds: 30,
               },
               {
                 test-type: Functional,
                 test-status: Success,
                 description: "Retry Needed | Exit Code Found",
-                exe-path: executable-monitor/test.out,
-                success-exit-code: ${{ env.time_exit_code }},
+                exe-path: executable-monitor/test_exit_current_minutes.out,
+                success-exit-code: RETRY_EXIT_CODE,
                 retry-attempts: 10,
-                timeout-seconds: 30,
+                timeout-seconds: 60,
               },
               {
                 test-type: Functional,
                 test-status: Success,
                 description: "Retry Needed | Success Line Found",
                 exe-path: executable-monitor/test_exit_current_minutes.out,
+                success-line: RETRY_SUCCESS_LINE,
                 retry-attempts: 10,
+                timeout-seconds: 60,
               },
               {
                 test-type: Functional,
@@ -91,8 +98,9 @@ jobs:
                 description: "Retry Needed | Exit Code and Success Line | Exit Code Found",
                 exe-path: executable-monitor/test_exit_current_minutes.out,
                 success-line: "LINE_THAT_WILL_NOT_PRINT",
-                success-exit-code: ${{ env.time_exit_code }},
+                success-exit-code: RETRY_EXIT_CODE,
                 retry-attempts: 10,
+                timeout-seconds: 60,
               },
               {
                 test-type: Functional,
@@ -100,9 +108,10 @@ jobs:
                 description: "Retry Needed | Exit Code and Success Line | Success Line Found",
                 # Use the EXE that doesn't exit with the current minutes
                 exe-path: executable-monitor/test.out,
-                success-line: "${{ env.time_success_line }}",
-                success-exit-code: ${{ env.time_exit_code }},
+                success-line: RETRY_SUCCESS_LINE,
+                success-exit-code: 1,
                 retry-attempts: 10,
+                timeout-seconds: 60,
               },
           ]
     runs-on: ${{ matrix.os }}
@@ -162,22 +171,39 @@ jobs:
         shell: bash
         run: |
           # Get times for future demos
-          echo "time_success_line=$(date --date='2 minutes' +%H:%M)" >> "$GITHUB_ENV"
-          echo "time_exit_code=$(date --date='5 minutes' +%M)" >> "$GITHUB_ENV"
+          if [[ "${{ matrix.inputs.success-line }}" == "RETRY_SUCCESS_LINE" ]]; then
+            echo "Setting Success Line to in the future"
+            echo "successLine=$(date --date='3 minutes' +%H:%M)" >> "$GITHUB_ENV"
+          else
+            echo "Keeping current success line"
+            echo "successLine=${{ matrix.inputs.success-line}}" >> "$GITHUB_ENV"
+          fi
+          if [[ "${{ matrix.inputs.success-exit-code }}" == "RETRY_EXIT_CODE" ]]; then
+            echo "Setting Exit Code to in the future"
+            echo "exitCode=$(date --date='3 minutes' +%M)" >> "$GITHUB_ENV"
+          else
+            echo "Keeping current Exit Code"
+            echo "exitCode=${{ matrix.inputs.success-exit-code}}" >> "$GITHUB_ENV"
+          fi
+          
+          
 
-      - name: "${{ matrix.inputs.test-type }} | ${{ matrix.inputs.test-status }} | ${{matric.inputs.description }} "
+      - env:
+          stepName: "${{ matrix.inputs.test-type }} | ${{ matrix.inputs.test-status }} | ${{matrix.inputs.description }}"
+        name: ${{ env.stepName }}
         id: test-executable-monitor-action-success-line
         uses: ./executable-monitor
         with:
-          exe-path: ${{ matrix.inputs. }}
+          exe-path: ${{ matrix.inputs.exe-path }}
           timeout-seconds: ${{ matrix.inputs.timeout-seconds }}
-          success-line: ${{ matrix.inputs.success-line }}
-          success-exit-code: ${{ matrix.inputs.success-exit-code }}
+          success-line: ${{ env.successLine }}
+          success-exit-code: ${{ env.exitCode}}
           retry-attempts: ${{ matrix.inputs.retry-attempts }}
           log-dir: ${{ matrix.inputs.log-dir}}
 
-  test-executable-monitor-success-cases:
+  test-executable-monitor-failure-cases:
     strategy:
+      fail-fast: false
       matrix:
         os: [ubuntu-latest, windows-latest]
         inputs:
@@ -186,13 +212,15 @@ jobs:
               test-type: API,
               test-status: Failure,
               description: "No Executable Provided",
+              timeout-seconds: 30,
             },
             {
               test-type: API,
               test-status: Failure,
               description: "No Success Condition Provided",
               exe-path: executable-monitor/test.out,
-              log-dir: logDirectory
+              log-dir: logDirectory,
+              timeout-seconds: 30,
             },
             {
               test-type: Functional,
@@ -253,51 +281,85 @@ jobs:
               timeout-seconds: 2,
               retry-attempts: 2,
             },
-        ]
+          ]
+    runs-on: ${{ matrix.os }}
+    steps:
+    - uses: actions/checkout@v3
+    - env:
+        stepName: Install Windows Build tools
+      name: ${{ env.stepName }}
+      if: runner.os == 'Windows'
+      id: install-windows-build-tools
+      uses: microsoft/setup-msbuild@v1.1
+  
+    - env:
+        stepName: Install Ubuntu Build Tools
+      name: ${{ env.stepName }}
+      if: runner.os == 'Linux'
+      id: install-ubuntu-build--tools
+      run: |
+        # Install Ubuntu Build Tools
+        echo "::group::${{ env.stepName }}"
+        sudo apt install build-essential
+        exitStatus=$?
+        echo "::endgroup::"
+        if [ "$exitStatus" = "0" ]; then
+          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        else
+          echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          exit 1
+        fi
 
-      - name: "${{ matrix.inputs.test-type }} | ${{ matrix.inputs.test-status }} | ${{matric.inputs.description }} "
-        id: test-failure-condition
-        uses: ./executable-monitor
-        continue-on-error: true
-        with:
-          exe-path: ${{ matrix.inputs. }}
-          timeout-seconds: ${{ matrix.inputs.timeout-seconds }}
-          success-line: ${{ matrix.inputs.success-line }}
-          success-exit-code: ${{ matrix.inputs.success-exit-code }}
-          retry-attempts: ${{ matrix.inputs.retry-attempts }}
-          log-dir: ${{ matrix.inputs.log-dir}}
+    - env:
+        stepName: Compile Executable Monitor Test Files
+      name: ${{ env.stepName }}
+      id: compile-executable-monitor-test-files
+      shell: bash
+      run: |
+        # ${{ env.stepName }}
+        echo "::group::${{ env.stepName }}"
+        gcc executable-monitor/test.c -o executable-monitor/test.out
+        gcc -DEXIT_WITH_MINUTES executable-monitor/test.c -o executable-monitor/test_exit_current_minutes.out
+        readlink -f executable-monitor/test.out
+        readlink -f executable-monitor/test_exit_current_minutes.out
+        exitStatus=$?
+        echo "::endgroup::"
+        if [ "$exitStatus" = "0" ]; then
+          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+        else
+          echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          exit 1
+        fi
 
-      - name: Check Failure Test Cases
-        id: check-failure-test-cases
-        shell: bash
-        run: |
-          # Check Failure Test Cases
-          set +e
-          exitStatus=0
-          if [ "${{ steps.test-failure-condition.outcome}}" = "failure" ]; then
-            echo -e "${{ env.bashPass }} ${{ matrix.inputs.test-type }} | ${{ matrix.inputs.description}} | Failed As Intended ${{ env.bashEnd }}"
-          else
-            echo -e "${{ env.bashFail }} ${{ matrix.inputs.test-type }} | ${{ matrix.inputs.description}} | Had Unexpected Pass ${{ env.bashEnd }}"
-            exitStatus=1
-          fi
-          #if [ "${{ steps.test-executable-monitor-API-no-success-metric.outcome}}" = "failure" ]; then
-          #  echo -e "${{ env.bashPass }}API Test | Failure Case | Retries, No Success Metric had outcome '${{ steps.test-executable-monitor-API-no-success-metric.outcome}}' as intended${{ env.bashEnd }}"
-          #else
-          #  echo -e "${{ env.bashFail }}API Test | Failure Case | Retries, No Success Metric had unexpected '${{ steps.test-executable-monitor-API-no-success-metric.outcome}}' exit condition${{ env.bashEnd }}"
-          #  exitStatus=1
-          #fi
-          #if [ "${{ steps.test-executable-monitor-API-no-exe-path.outcome}}" = "failure" ]; then
-          #  echo -e "${{ env.bashPass }}API Test | Failure Case | No Exe Path had outcome '${{ steps.test-executable-monitor-API-no-exe-path.outcome}}' as intended${{ env.bashEnd }}"
-          #else
-          #  echo -e "${{ env.bashFail }}API Test | Failure Case | No Exe Path had unexpected '${{ steps.test-executable-monitor-API-no-exe-path.outcome}}' exit condition${{ env.bashEnd }}"
-          #  exitStatus=1
-          #fi
-          #if [ "$exitStatus" = "0" ]; then
-          #  echo -e "${{ env.bashPass }}All tests failed as intended${{ env.bashEnd }}"
-          #else
-          #  echo -e "${{ env.bashFail }}A test that should have failed passed${{ env.bashEnd }}"
-          #  exit 1
-          #fi
+    - env:
+        stepName: "${{ matrix.inputs.test-type }} | ${{ matrix.inputs.test-status }} | ${{matrix.inputs.description }} "
+      name: ${{ env.stepName }}
+      id: test-failure-condition
+      uses: ./executable-monitor
+      continue-on-error: true
+      with:
+        exe-path: ${{ matrix.inputs.exe-path }}
+        timeout-seconds: ${{ matrix.inputs.timeout-seconds }}
+        success-line: ${{ matrix.inputs.success-line }}
+        success-exit-code: ${{ matrix.inputs.success-exit-code }}
+        retry-attempts: ${{ matrix.inputs.retry-attempts }}
+        log-dir: ${{ matrix.inputs.log-dir}}
+
+    - env:
+        stepName: Check Failure Test Cases
+      name: ${{ env.stepName }}
+      id: check-failure-test-cases
+      shell: bash
+      run: |
+        # Check Failure Test Cases
+        set +e
+        exitStatus=0
+        if [ "${{ steps.test-failure-condition.outcome}}" = "failure" ]; then
+          echo -e "${{ env.bashPass }} ${{ matrix.inputs.test-type }} | ${{ matrix.inputs.description}} | Failed As Intended ${{ env.bashEnd }}"
+        else
+          echo -e "${{ env.bashFail }} ${{ matrix.inputs.test-type }} | ${{ matrix.inputs.description}} | Had Unexpected Pass ${{ env.bashEnd }}"
+        exitStatus=1
+        fi
 
   test-complexity-check:
     runs-on: ubuntu-latest
