Include the option to exclude urls, add in tests for it

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -109,7 +109,7 @@ jobs:
           exe-path: executable-monitor/test.out
           success-line: "SLEEPING FOR 6 SECONDS"
           timeout-seconds: 20
-      
+
       - name: Functional Test | Success Case | No Retries, No Success Line, Exit Code
         id: test-executable-monitor-action-no-retry-attempts-exit-code
         uses: ./executable-monitor
@@ -125,7 +125,7 @@ jobs:
           exe-path: executable-monitor/test.out
           success-line: "SLEEPING FOR 6 SECONDS"
           retry-attempts: 2
-          
+
       - name: API Test | Success Case | Retries, No Success Line, Exit Code, Use Default Timeout
         id: test-executable-monitor-action-no-success-line-no-timeout
         uses: ./executable-monitor
@@ -328,17 +328,58 @@ jobs:
   test-link-verifier:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
+
       - name: Setup python environment
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.11.0'
-      - name: Test link verifier action
+        uses: actions/setup-python@v3
+
+      - env:
+          stepName: "Functional | Success | Link Verifier Works & Excludes Directory"
+        name: ${{ env.stepName }}
+        id: link-verifier-success-case
         uses: ./link-verifier
         with:
           path: ./
-          exclude-dirs: complexity,formatting
-          include-file-types: .c,.html
+          exclude-dirs: complexity, formatting, badFiles
+          allowlist-file: link-verifier/badUrls.md
+
+      - env:
+          stepName: "Functional | Success | Link being Excluded"
+        name: ${{ env.stepName }}
+        id: link-verifier-exclude-url-success-case
+        uses: ./link-verifier
+        with:
+          path: ./
+          exclude-dirs: complexity, formatting
+          exclude-urls: https://dummy-url.com/ota.bin, https://dummy-url.com/ota.com, https://dummy-url-three.com/ota.bin, https://github.com/FreeRTOS/A-Repo-That-Wins-You-The-Lottery
+
+      - env:
+          stepName: "Functional | Failure | Link Does Not Exist"
+        name: ${{ env.stepName }}
+        id: link-verifier-fail-case
+        continue-on-error: true
+        uses: ./link-verifier
+        with:
+          path: ./
+          exclude-dirs: complexity, formatting
+          allowlist-file: badUrls.md
+
+      - env:
+          stepName: Check Failure Test Case
+        name: ${{ env.stepName }}
+        id: check-failure-test-cases
+        shell: bash
+        run: |
+          # ${{ env.stepName }}
+          exitStatus=0
+          if [ "${{ steps.link-verifier-fail-case.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} Functional | Failure | Link Does Not Exist | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} Functional | Failure | Link Does Not Exist | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          exit $exitStatus
+
   test-manifest-verifier:
     runs-on: ubuntu-latest
     steps:
@@ -353,7 +394,7 @@ jobs:
           repository: FreeRTOS/FreeRTOS
           ref: '202107.00'
           path: FreeRTOS
-          submodules: recursive      
+          submodules: recursive
       - name: Test manifest verifier
         uses: ./manifest-verifier
         with:
